steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west1-docker.pkg.dev/${PROJECT_ID}/release/operator:${_IMAGE_TAG}', '.', '-f', 'Dockerfile.operator']
images: ['us-west1-docker.pkg.dev/${PROJECT_ID}/release/operator:${_IMAGE_TAG}']
substitutions:
  _IMAGE_TAG: latest #default value