// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: dataplane/proto/sai/ipsec.proto

package sai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpsecAttr int32

const (
	IpsecAttr_IPSEC_ATTR_UNSPECIFIED                                IpsecAttr = 0
	IpsecAttr_IPSEC_ATTR_TERM_REMOTE_IP_MATCH_SUPPORTED             IpsecAttr = 1
	IpsecAttr_IPSEC_ATTR_SWITCHING_MODE_CUT_THROUGH_SUPPORTED       IpsecAttr = 2
	IpsecAttr_IPSEC_ATTR_SWITCHING_MODE_STORE_AND_FORWARD_SUPPORTED IpsecAttr = 3
	IpsecAttr_IPSEC_ATTR_STATS_MODE_READ_SUPPORTED                  IpsecAttr = 4
	IpsecAttr_IPSEC_ATTR_STATS_MODE_READ_CLEAR_SUPPORTED            IpsecAttr = 5
	IpsecAttr_IPSEC_ATTR_SN_32BIT_SUPPORTED                         IpsecAttr = 6
	IpsecAttr_IPSEC_ATTR_ESN_64BIT_SUPPORTED                        IpsecAttr = 7
	IpsecAttr_IPSEC_ATTR_SUPPORTED_CIPHER_LIST                      IpsecAttr = 8
	IpsecAttr_IPSEC_ATTR_SYSTEM_SIDE_MTU                            IpsecAttr = 9
	IpsecAttr_IPSEC_ATTR_WARM_BOOT_SUPPORTED                        IpsecAttr = 10
	IpsecAttr_IPSEC_ATTR_WARM_BOOT_ENABLE                           IpsecAttr = 11
	IpsecAttr_IPSEC_ATTR_EXTERNAL_SA_INDEX_ENABLE                   IpsecAttr = 12
	IpsecAttr_IPSEC_ATTR_CTAG_TPID                                  IpsecAttr = 13
	IpsecAttr_IPSEC_ATTR_STAG_TPID                                  IpsecAttr = 14
	IpsecAttr_IPSEC_ATTR_MAX_VLAN_TAGS_PARSED                       IpsecAttr = 15
	IpsecAttr_IPSEC_ATTR_OCTET_COUNT_HIGH_WATERMARK                 IpsecAttr = 16
	IpsecAttr_IPSEC_ATTR_OCTET_COUNT_LOW_WATERMARK                  IpsecAttr = 17
	IpsecAttr_IPSEC_ATTR_STATS_MODE                                 IpsecAttr = 18
	IpsecAttr_IPSEC_ATTR_AVAILABLE_IPSEC_SA                         IpsecAttr = 19
	IpsecAttr_IPSEC_ATTR_SA_LIST                                    IpsecAttr = 20
)

// Enum value maps for IpsecAttr.
var (
	IpsecAttr_name = map[int32]string{
		0:  "IPSEC_ATTR_UNSPECIFIED",
		1:  "IPSEC_ATTR_TERM_REMOTE_IP_MATCH_SUPPORTED",
		2:  "IPSEC_ATTR_SWITCHING_MODE_CUT_THROUGH_SUPPORTED",
		3:  "IPSEC_ATTR_SWITCHING_MODE_STORE_AND_FORWARD_SUPPORTED",
		4:  "IPSEC_ATTR_STATS_MODE_READ_SUPPORTED",
		5:  "IPSEC_ATTR_STATS_MODE_READ_CLEAR_SUPPORTED",
		6:  "IPSEC_ATTR_SN_32BIT_SUPPORTED",
		7:  "IPSEC_ATTR_ESN_64BIT_SUPPORTED",
		8:  "IPSEC_ATTR_SUPPORTED_CIPHER_LIST",
		9:  "IPSEC_ATTR_SYSTEM_SIDE_MTU",
		10: "IPSEC_ATTR_WARM_BOOT_SUPPORTED",
		11: "IPSEC_ATTR_WARM_BOOT_ENABLE",
		12: "IPSEC_ATTR_EXTERNAL_SA_INDEX_ENABLE",
		13: "IPSEC_ATTR_CTAG_TPID",
		14: "IPSEC_ATTR_STAG_TPID",
		15: "IPSEC_ATTR_MAX_VLAN_TAGS_PARSED",
		16: "IPSEC_ATTR_OCTET_COUNT_HIGH_WATERMARK",
		17: "IPSEC_ATTR_OCTET_COUNT_LOW_WATERMARK",
		18: "IPSEC_ATTR_STATS_MODE",
		19: "IPSEC_ATTR_AVAILABLE_IPSEC_SA",
		20: "IPSEC_ATTR_SA_LIST",
	}
	IpsecAttr_value = map[string]int32{
		"IPSEC_ATTR_UNSPECIFIED":                                0,
		"IPSEC_ATTR_TERM_REMOTE_IP_MATCH_SUPPORTED":             1,
		"IPSEC_ATTR_SWITCHING_MODE_CUT_THROUGH_SUPPORTED":       2,
		"IPSEC_ATTR_SWITCHING_MODE_STORE_AND_FORWARD_SUPPORTED": 3,
		"IPSEC_ATTR_STATS_MODE_READ_SUPPORTED":                  4,
		"IPSEC_ATTR_STATS_MODE_READ_CLEAR_SUPPORTED":            5,
		"IPSEC_ATTR_SN_32BIT_SUPPORTED":                         6,
		"IPSEC_ATTR_ESN_64BIT_SUPPORTED":                        7,
		"IPSEC_ATTR_SUPPORTED_CIPHER_LIST":                      8,
		"IPSEC_ATTR_SYSTEM_SIDE_MTU":                            9,
		"IPSEC_ATTR_WARM_BOOT_SUPPORTED":                        10,
		"IPSEC_ATTR_WARM_BOOT_ENABLE":                           11,
		"IPSEC_ATTR_EXTERNAL_SA_INDEX_ENABLE":                   12,
		"IPSEC_ATTR_CTAG_TPID":                                  13,
		"IPSEC_ATTR_STAG_TPID":                                  14,
		"IPSEC_ATTR_MAX_VLAN_TAGS_PARSED":                       15,
		"IPSEC_ATTR_OCTET_COUNT_HIGH_WATERMARK":                 16,
		"IPSEC_ATTR_OCTET_COUNT_LOW_WATERMARK":                  17,
		"IPSEC_ATTR_STATS_MODE":                                 18,
		"IPSEC_ATTR_AVAILABLE_IPSEC_SA":                         19,
		"IPSEC_ATTR_SA_LIST":                                    20,
	}
)

func (x IpsecAttr) Enum() *IpsecAttr {
	p := new(IpsecAttr)
	*p = x
	return p
}

func (x IpsecAttr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpsecAttr) Descriptor() protoreflect.EnumDescriptor {
	return file_dataplane_proto_sai_ipsec_proto_enumTypes[0].Descriptor()
}

func (IpsecAttr) Type() protoreflect.EnumType {
	return &file_dataplane_proto_sai_ipsec_proto_enumTypes[0]
}

func (x IpsecAttr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpsecAttr.Descriptor instead.
func (IpsecAttr) EnumDescriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{0}
}

type IpsecPortAttr int32

const (
	IpsecPortAttr_IPSEC_PORT_ATTR_UNSPECIFIED                 IpsecPortAttr = 0
	IpsecPortAttr_IPSEC_PORT_ATTR_PORT_ID                     IpsecPortAttr = 1
	IpsecPortAttr_IPSEC_PORT_ATTR_CTAG_ENABLE                 IpsecPortAttr = 2
	IpsecPortAttr_IPSEC_PORT_ATTR_STAG_ENABLE                 IpsecPortAttr = 3
	IpsecPortAttr_IPSEC_PORT_ATTR_NATIVE_VLAN_ID              IpsecPortAttr = 4
	IpsecPortAttr_IPSEC_PORT_ATTR_VRF_FROM_PACKET_VLAN_ENABLE IpsecPortAttr = 5
	IpsecPortAttr_IPSEC_PORT_ATTR_SWITCH_SWITCHING_MODE       IpsecPortAttr = 6
	IpsecPortAttr_IPSEC_PORT_ATTR_STATS_COUNT_MODE            IpsecPortAttr = 7
	IpsecPortAttr_IPSEC_PORT_ATTR_SELECTIVE_COUNTER_LIST      IpsecPortAttr = 8
)

// Enum value maps for IpsecPortAttr.
var (
	IpsecPortAttr_name = map[int32]string{
		0: "IPSEC_PORT_ATTR_UNSPECIFIED",
		1: "IPSEC_PORT_ATTR_PORT_ID",
		2: "IPSEC_PORT_ATTR_CTAG_ENABLE",
		3: "IPSEC_PORT_ATTR_STAG_ENABLE",
		4: "IPSEC_PORT_ATTR_NATIVE_VLAN_ID",
		5: "IPSEC_PORT_ATTR_VRF_FROM_PACKET_VLAN_ENABLE",
		6: "IPSEC_PORT_ATTR_SWITCH_SWITCHING_MODE",
		7: "IPSEC_PORT_ATTR_STATS_COUNT_MODE",
		8: "IPSEC_PORT_ATTR_SELECTIVE_COUNTER_LIST",
	}
	IpsecPortAttr_value = map[string]int32{
		"IPSEC_PORT_ATTR_UNSPECIFIED":                 0,
		"IPSEC_PORT_ATTR_PORT_ID":                     1,
		"IPSEC_PORT_ATTR_CTAG_ENABLE":                 2,
		"IPSEC_PORT_ATTR_STAG_ENABLE":                 3,
		"IPSEC_PORT_ATTR_NATIVE_VLAN_ID":              4,
		"IPSEC_PORT_ATTR_VRF_FROM_PACKET_VLAN_ENABLE": 5,
		"IPSEC_PORT_ATTR_SWITCH_SWITCHING_MODE":       6,
		"IPSEC_PORT_ATTR_STATS_COUNT_MODE":            7,
		"IPSEC_PORT_ATTR_SELECTIVE_COUNTER_LIST":      8,
	}
)

func (x IpsecPortAttr) Enum() *IpsecPortAttr {
	p := new(IpsecPortAttr)
	*p = x
	return p
}

func (x IpsecPortAttr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpsecPortAttr) Descriptor() protoreflect.EnumDescriptor {
	return file_dataplane_proto_sai_ipsec_proto_enumTypes[1].Descriptor()
}

func (IpsecPortAttr) Type() protoreflect.EnumType {
	return &file_dataplane_proto_sai_ipsec_proto_enumTypes[1]
}

func (x IpsecPortAttr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpsecPortAttr.Descriptor instead.
func (IpsecPortAttr) EnumDescriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{1}
}

type IpsecSaAttr int32

const (
	IpsecSaAttr_IPSEC_SA_ATTR_UNSPECIFIED                    IpsecSaAttr = 0
	IpsecSaAttr_IPSEC_SA_ATTR_IPSEC_DIRECTION                IpsecSaAttr = 1
	IpsecSaAttr_IPSEC_SA_ATTR_IPSEC_ID                       IpsecSaAttr = 2
	IpsecSaAttr_IPSEC_SA_ATTR_OCTET_COUNT_STATUS             IpsecSaAttr = 3
	IpsecSaAttr_IPSEC_SA_ATTR_EXTERNAL_SA_INDEX              IpsecSaAttr = 4
	IpsecSaAttr_IPSEC_SA_ATTR_SA_INDEX                       IpsecSaAttr = 5
	IpsecSaAttr_IPSEC_SA_ATTR_IPSEC_PORT_LIST                IpsecSaAttr = 6
	IpsecSaAttr_IPSEC_SA_ATTR_IPSEC_SPI                      IpsecSaAttr = 7
	IpsecSaAttr_IPSEC_SA_ATTR_IPSEC_ESN_ENABLE               IpsecSaAttr = 8
	IpsecSaAttr_IPSEC_SA_ATTR_IPSEC_CIPHER                   IpsecSaAttr = 9
	IpsecSaAttr_IPSEC_SA_ATTR_ENCRYPT_KEY                    IpsecSaAttr = 10
	IpsecSaAttr_IPSEC_SA_ATTR_SALT                           IpsecSaAttr = 11
	IpsecSaAttr_IPSEC_SA_ATTR_AUTH_KEY                       IpsecSaAttr = 12
	IpsecSaAttr_IPSEC_SA_ATTR_IPSEC_REPLAY_PROTECTION_ENABLE IpsecSaAttr = 13
	IpsecSaAttr_IPSEC_SA_ATTR_IPSEC_REPLAY_PROTECTION_WINDOW IpsecSaAttr = 14
	IpsecSaAttr_IPSEC_SA_ATTR_TERM_DST_IP                    IpsecSaAttr = 15
	IpsecSaAttr_IPSEC_SA_ATTR_TERM_VLAN_ID_ENABLE            IpsecSaAttr = 16
	IpsecSaAttr_IPSEC_SA_ATTR_TERM_VLAN_ID                   IpsecSaAttr = 17
	IpsecSaAttr_IPSEC_SA_ATTR_TERM_SRC_IP_ENABLE             IpsecSaAttr = 18
	IpsecSaAttr_IPSEC_SA_ATTR_TERM_SRC_IP                    IpsecSaAttr = 19
	IpsecSaAttr_IPSEC_SA_ATTR_EGRESS_ESN                     IpsecSaAttr = 20
	IpsecSaAttr_IPSEC_SA_ATTR_MINIMUM_INGRESS_ESN            IpsecSaAttr = 21
	IpsecSaAttr_IPSEC_SA_ATTR_STATS_COUNT_MODE               IpsecSaAttr = 22
	IpsecSaAttr_IPSEC_SA_ATTR_SELECTIVE_COUNTER_LIST         IpsecSaAttr = 23
)

// Enum value maps for IpsecSaAttr.
var (
	IpsecSaAttr_name = map[int32]string{
		0:  "IPSEC_SA_ATTR_UNSPECIFIED",
		1:  "IPSEC_SA_ATTR_IPSEC_DIRECTION",
		2:  "IPSEC_SA_ATTR_IPSEC_ID",
		3:  "IPSEC_SA_ATTR_OCTET_COUNT_STATUS",
		4:  "IPSEC_SA_ATTR_EXTERNAL_SA_INDEX",
		5:  "IPSEC_SA_ATTR_SA_INDEX",
		6:  "IPSEC_SA_ATTR_IPSEC_PORT_LIST",
		7:  "IPSEC_SA_ATTR_IPSEC_SPI",
		8:  "IPSEC_SA_ATTR_IPSEC_ESN_ENABLE",
		9:  "IPSEC_SA_ATTR_IPSEC_CIPHER",
		10: "IPSEC_SA_ATTR_ENCRYPT_KEY",
		11: "IPSEC_SA_ATTR_SALT",
		12: "IPSEC_SA_ATTR_AUTH_KEY",
		13: "IPSEC_SA_ATTR_IPSEC_REPLAY_PROTECTION_ENABLE",
		14: "IPSEC_SA_ATTR_IPSEC_REPLAY_PROTECTION_WINDOW",
		15: "IPSEC_SA_ATTR_TERM_DST_IP",
		16: "IPSEC_SA_ATTR_TERM_VLAN_ID_ENABLE",
		17: "IPSEC_SA_ATTR_TERM_VLAN_ID",
		18: "IPSEC_SA_ATTR_TERM_SRC_IP_ENABLE",
		19: "IPSEC_SA_ATTR_TERM_SRC_IP",
		20: "IPSEC_SA_ATTR_EGRESS_ESN",
		21: "IPSEC_SA_ATTR_MINIMUM_INGRESS_ESN",
		22: "IPSEC_SA_ATTR_STATS_COUNT_MODE",
		23: "IPSEC_SA_ATTR_SELECTIVE_COUNTER_LIST",
	}
	IpsecSaAttr_value = map[string]int32{
		"IPSEC_SA_ATTR_UNSPECIFIED":                    0,
		"IPSEC_SA_ATTR_IPSEC_DIRECTION":                1,
		"IPSEC_SA_ATTR_IPSEC_ID":                       2,
		"IPSEC_SA_ATTR_OCTET_COUNT_STATUS":             3,
		"IPSEC_SA_ATTR_EXTERNAL_SA_INDEX":              4,
		"IPSEC_SA_ATTR_SA_INDEX":                       5,
		"IPSEC_SA_ATTR_IPSEC_PORT_LIST":                6,
		"IPSEC_SA_ATTR_IPSEC_SPI":                      7,
		"IPSEC_SA_ATTR_IPSEC_ESN_ENABLE":               8,
		"IPSEC_SA_ATTR_IPSEC_CIPHER":                   9,
		"IPSEC_SA_ATTR_ENCRYPT_KEY":                    10,
		"IPSEC_SA_ATTR_SALT":                           11,
		"IPSEC_SA_ATTR_AUTH_KEY":                       12,
		"IPSEC_SA_ATTR_IPSEC_REPLAY_PROTECTION_ENABLE": 13,
		"IPSEC_SA_ATTR_IPSEC_REPLAY_PROTECTION_WINDOW": 14,
		"IPSEC_SA_ATTR_TERM_DST_IP":                    15,
		"IPSEC_SA_ATTR_TERM_VLAN_ID_ENABLE":            16,
		"IPSEC_SA_ATTR_TERM_VLAN_ID":                   17,
		"IPSEC_SA_ATTR_TERM_SRC_IP_ENABLE":             18,
		"IPSEC_SA_ATTR_TERM_SRC_IP":                    19,
		"IPSEC_SA_ATTR_EGRESS_ESN":                     20,
		"IPSEC_SA_ATTR_MINIMUM_INGRESS_ESN":            21,
		"IPSEC_SA_ATTR_STATS_COUNT_MODE":               22,
		"IPSEC_SA_ATTR_SELECTIVE_COUNTER_LIST":         23,
	}
)

func (x IpsecSaAttr) Enum() *IpsecSaAttr {
	p := new(IpsecSaAttr)
	*p = x
	return p
}

func (x IpsecSaAttr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpsecSaAttr) Descriptor() protoreflect.EnumDescriptor {
	return file_dataplane_proto_sai_ipsec_proto_enumTypes[2].Descriptor()
}

func (IpsecSaAttr) Type() protoreflect.EnumType {
	return &file_dataplane_proto_sai_ipsec_proto_enumTypes[2]
}

func (x IpsecSaAttr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpsecSaAttr.Descriptor instead.
func (IpsecSaAttr) EnumDescriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{2}
}

type CreateIpsecRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Switch                  uint64                 `protobuf:"varint,1,opt,name=switch,proto3" json:"switch,omitempty"`
	WarmBootEnable          *bool                  `protobuf:"varint,2,opt,name=warm_boot_enable,json=warmBootEnable,proto3,oneof" json:"warm_boot_enable,omitempty"`
	ExternalSaIndexEnable   *bool                  `protobuf:"varint,3,opt,name=external_sa_index_enable,json=externalSaIndexEnable,proto3,oneof" json:"external_sa_index_enable,omitempty"`
	CtagTpid                *uint32                `protobuf:"varint,4,opt,name=ctag_tpid,json=ctagTpid,proto3,oneof" json:"ctag_tpid,omitempty"`
	StagTpid                *uint32                `protobuf:"varint,5,opt,name=stag_tpid,json=stagTpid,proto3,oneof" json:"stag_tpid,omitempty"`
	MaxVlanTagsParsed       *uint32                `protobuf:"varint,6,opt,name=max_vlan_tags_parsed,json=maxVlanTagsParsed,proto3,oneof" json:"max_vlan_tags_parsed,omitempty"`
	OctetCountHighWatermark *uint64                `protobuf:"varint,7,opt,name=octet_count_high_watermark,json=octetCountHighWatermark,proto3,oneof" json:"octet_count_high_watermark,omitempty"`
	OctetCountLowWatermark  *uint64                `protobuf:"varint,8,opt,name=octet_count_low_watermark,json=octetCountLowWatermark,proto3,oneof" json:"octet_count_low_watermark,omitempty"`
	StatsMode               *StatsMode             `protobuf:"varint,9,opt,name=stats_mode,json=statsMode,proto3,enum=lemming.dataplane.sai.StatsMode,oneof" json:"stats_mode,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CreateIpsecRequest) Reset() {
	*x = CreateIpsecRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIpsecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIpsecRequest) ProtoMessage() {}

func (x *CreateIpsecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIpsecRequest.ProtoReflect.Descriptor instead.
func (*CreateIpsecRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIpsecRequest) GetSwitch() uint64 {
	if x != nil {
		return x.Switch
	}
	return 0
}

func (x *CreateIpsecRequest) GetWarmBootEnable() bool {
	if x != nil && x.WarmBootEnable != nil {
		return *x.WarmBootEnable
	}
	return false
}

func (x *CreateIpsecRequest) GetExternalSaIndexEnable() bool {
	if x != nil && x.ExternalSaIndexEnable != nil {
		return *x.ExternalSaIndexEnable
	}
	return false
}

func (x *CreateIpsecRequest) GetCtagTpid() uint32 {
	if x != nil && x.CtagTpid != nil {
		return *x.CtagTpid
	}
	return 0
}

func (x *CreateIpsecRequest) GetStagTpid() uint32 {
	if x != nil && x.StagTpid != nil {
		return *x.StagTpid
	}
	return 0
}

func (x *CreateIpsecRequest) GetMaxVlanTagsParsed() uint32 {
	if x != nil && x.MaxVlanTagsParsed != nil {
		return *x.MaxVlanTagsParsed
	}
	return 0
}

func (x *CreateIpsecRequest) GetOctetCountHighWatermark() uint64 {
	if x != nil && x.OctetCountHighWatermark != nil {
		return *x.OctetCountHighWatermark
	}
	return 0
}

func (x *CreateIpsecRequest) GetOctetCountLowWatermark() uint64 {
	if x != nil && x.OctetCountLowWatermark != nil {
		return *x.OctetCountLowWatermark
	}
	return 0
}

func (x *CreateIpsecRequest) GetStatsMode() StatsMode {
	if x != nil && x.StatsMode != nil {
		return *x.StatsMode
	}
	return StatsMode_STATS_MODE_UNSPECIFIED
}

type CreateIpsecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIpsecResponse) Reset() {
	*x = CreateIpsecResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIpsecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIpsecResponse) ProtoMessage() {}

func (x *CreateIpsecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIpsecResponse.ProtoReflect.Descriptor instead.
func (*CreateIpsecResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIpsecResponse) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveIpsecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIpsecRequest) Reset() {
	*x = RemoveIpsecRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIpsecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIpsecRequest) ProtoMessage() {}

func (x *RemoveIpsecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIpsecRequest.ProtoReflect.Descriptor instead.
func (*RemoveIpsecRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveIpsecRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveIpsecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIpsecResponse) Reset() {
	*x = RemoveIpsecResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIpsecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIpsecResponse) ProtoMessage() {}

func (x *RemoveIpsecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIpsecResponse.ProtoReflect.Descriptor instead.
func (*RemoveIpsecResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{3}
}

type SetIpsecAttributeRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Oid                     uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	WarmBootEnable          *bool                  `protobuf:"varint,2,opt,name=warm_boot_enable,json=warmBootEnable,proto3,oneof" json:"warm_boot_enable,omitempty"`
	CtagTpid                *uint32                `protobuf:"varint,3,opt,name=ctag_tpid,json=ctagTpid,proto3,oneof" json:"ctag_tpid,omitempty"`
	StagTpid                *uint32                `protobuf:"varint,4,opt,name=stag_tpid,json=stagTpid,proto3,oneof" json:"stag_tpid,omitempty"`
	MaxVlanTagsParsed       *uint32                `protobuf:"varint,5,opt,name=max_vlan_tags_parsed,json=maxVlanTagsParsed,proto3,oneof" json:"max_vlan_tags_parsed,omitempty"`
	OctetCountHighWatermark *uint64                `protobuf:"varint,6,opt,name=octet_count_high_watermark,json=octetCountHighWatermark,proto3,oneof" json:"octet_count_high_watermark,omitempty"`
	OctetCountLowWatermark  *uint64                `protobuf:"varint,7,opt,name=octet_count_low_watermark,json=octetCountLowWatermark,proto3,oneof" json:"octet_count_low_watermark,omitempty"`
	StatsMode               *StatsMode             `protobuf:"varint,8,opt,name=stats_mode,json=statsMode,proto3,enum=lemming.dataplane.sai.StatsMode,oneof" json:"stats_mode,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SetIpsecAttributeRequest) Reset() {
	*x = SetIpsecAttributeRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetIpsecAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIpsecAttributeRequest) ProtoMessage() {}

func (x *SetIpsecAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIpsecAttributeRequest.ProtoReflect.Descriptor instead.
func (*SetIpsecAttributeRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{4}
}

func (x *SetIpsecAttributeRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *SetIpsecAttributeRequest) GetWarmBootEnable() bool {
	if x != nil && x.WarmBootEnable != nil {
		return *x.WarmBootEnable
	}
	return false
}

func (x *SetIpsecAttributeRequest) GetCtagTpid() uint32 {
	if x != nil && x.CtagTpid != nil {
		return *x.CtagTpid
	}
	return 0
}

func (x *SetIpsecAttributeRequest) GetStagTpid() uint32 {
	if x != nil && x.StagTpid != nil {
		return *x.StagTpid
	}
	return 0
}

func (x *SetIpsecAttributeRequest) GetMaxVlanTagsParsed() uint32 {
	if x != nil && x.MaxVlanTagsParsed != nil {
		return *x.MaxVlanTagsParsed
	}
	return 0
}

func (x *SetIpsecAttributeRequest) GetOctetCountHighWatermark() uint64 {
	if x != nil && x.OctetCountHighWatermark != nil {
		return *x.OctetCountHighWatermark
	}
	return 0
}

func (x *SetIpsecAttributeRequest) GetOctetCountLowWatermark() uint64 {
	if x != nil && x.OctetCountLowWatermark != nil {
		return *x.OctetCountLowWatermark
	}
	return 0
}

func (x *SetIpsecAttributeRequest) GetStatsMode() StatsMode {
	if x != nil && x.StatsMode != nil {
		return *x.StatsMode
	}
	return StatsMode_STATS_MODE_UNSPECIFIED
}

type SetIpsecAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetIpsecAttributeResponse) Reset() {
	*x = SetIpsecAttributeResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetIpsecAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIpsecAttributeResponse) ProtoMessage() {}

func (x *SetIpsecAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIpsecAttributeResponse.ProtoReflect.Descriptor instead.
func (*SetIpsecAttributeResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{5}
}

type GetIpsecAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	AttrType      []IpsecAttr            `protobuf:"varint,2,rep,packed,name=attr_type,json=attrType,proto3,enum=lemming.dataplane.sai.IpsecAttr" json:"attr_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpsecAttributeRequest) Reset() {
	*x = GetIpsecAttributeRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpsecAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpsecAttributeRequest) ProtoMessage() {}

func (x *GetIpsecAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpsecAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetIpsecAttributeRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{6}
}

func (x *GetIpsecAttributeRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *GetIpsecAttributeRequest) GetAttrType() []IpsecAttr {
	if x != nil {
		return x.AttrType
	}
	return nil
}

type GetIpsecAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *IpsecAttribute        `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpsecAttributeResponse) Reset() {
	*x = GetIpsecAttributeResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpsecAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpsecAttributeResponse) ProtoMessage() {}

func (x *GetIpsecAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpsecAttributeResponse.ProtoReflect.Descriptor instead.
func (*GetIpsecAttributeResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{7}
}

func (x *GetIpsecAttributeResponse) GetAttr() *IpsecAttribute {
	if x != nil {
		return x.Attr
	}
	return nil
}

type CreateIpsecPortRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Switch                  uint64                 `protobuf:"varint,1,opt,name=switch,proto3" json:"switch,omitempty"`
	PortId                  *uint64                `protobuf:"varint,2,opt,name=port_id,json=portId,proto3,oneof" json:"port_id,omitempty"`
	CtagEnable              *bool                  `protobuf:"varint,3,opt,name=ctag_enable,json=ctagEnable,proto3,oneof" json:"ctag_enable,omitempty"`
	StagEnable              *bool                  `protobuf:"varint,4,opt,name=stag_enable,json=stagEnable,proto3,oneof" json:"stag_enable,omitempty"`
	NativeVlanId            *uint32                `protobuf:"varint,5,opt,name=native_vlan_id,json=nativeVlanId,proto3,oneof" json:"native_vlan_id,omitempty"`
	VrfFromPacketVlanEnable *bool                  `protobuf:"varint,6,opt,name=vrf_from_packet_vlan_enable,json=vrfFromPacketVlanEnable,proto3,oneof" json:"vrf_from_packet_vlan_enable,omitempty"`
	SwitchSwitchingMode     *SwitchSwitchingMode   `protobuf:"varint,7,opt,name=switch_switching_mode,json=switchSwitchingMode,proto3,enum=lemming.dataplane.sai.SwitchSwitchingMode,oneof" json:"switch_switching_mode,omitempty"`
	StatsCountMode          *StatsCountMode        `protobuf:"varint,8,opt,name=stats_count_mode,json=statsCountMode,proto3,enum=lemming.dataplane.sai.StatsCountMode,oneof" json:"stats_count_mode,omitempty"`
	SelectiveCounterList    []uint64               `protobuf:"varint,9,rep,packed,name=selective_counter_list,json=selectiveCounterList,proto3" json:"selective_counter_list,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CreateIpsecPortRequest) Reset() {
	*x = CreateIpsecPortRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIpsecPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIpsecPortRequest) ProtoMessage() {}

func (x *CreateIpsecPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIpsecPortRequest.ProtoReflect.Descriptor instead.
func (*CreateIpsecPortRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{8}
}

func (x *CreateIpsecPortRequest) GetSwitch() uint64 {
	if x != nil {
		return x.Switch
	}
	return 0
}

func (x *CreateIpsecPortRequest) GetPortId() uint64 {
	if x != nil && x.PortId != nil {
		return *x.PortId
	}
	return 0
}

func (x *CreateIpsecPortRequest) GetCtagEnable() bool {
	if x != nil && x.CtagEnable != nil {
		return *x.CtagEnable
	}
	return false
}

func (x *CreateIpsecPortRequest) GetStagEnable() bool {
	if x != nil && x.StagEnable != nil {
		return *x.StagEnable
	}
	return false
}

func (x *CreateIpsecPortRequest) GetNativeVlanId() uint32 {
	if x != nil && x.NativeVlanId != nil {
		return *x.NativeVlanId
	}
	return 0
}

func (x *CreateIpsecPortRequest) GetVrfFromPacketVlanEnable() bool {
	if x != nil && x.VrfFromPacketVlanEnable != nil {
		return *x.VrfFromPacketVlanEnable
	}
	return false
}

func (x *CreateIpsecPortRequest) GetSwitchSwitchingMode() SwitchSwitchingMode {
	if x != nil && x.SwitchSwitchingMode != nil {
		return *x.SwitchSwitchingMode
	}
	return SwitchSwitchingMode_SWITCH_SWITCHING_MODE_UNSPECIFIED
}

func (x *CreateIpsecPortRequest) GetStatsCountMode() StatsCountMode {
	if x != nil && x.StatsCountMode != nil {
		return *x.StatsCountMode
	}
	return StatsCountMode_STATS_COUNT_MODE_UNSPECIFIED
}

func (x *CreateIpsecPortRequest) GetSelectiveCounterList() []uint64 {
	if x != nil {
		return x.SelectiveCounterList
	}
	return nil
}

type CreateIpsecPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIpsecPortResponse) Reset() {
	*x = CreateIpsecPortResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIpsecPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIpsecPortResponse) ProtoMessage() {}

func (x *CreateIpsecPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIpsecPortResponse.ProtoReflect.Descriptor instead.
func (*CreateIpsecPortResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{9}
}

func (x *CreateIpsecPortResponse) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveIpsecPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIpsecPortRequest) Reset() {
	*x = RemoveIpsecPortRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIpsecPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIpsecPortRequest) ProtoMessage() {}

func (x *RemoveIpsecPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIpsecPortRequest.ProtoReflect.Descriptor instead.
func (*RemoveIpsecPortRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveIpsecPortRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveIpsecPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIpsecPortResponse) Reset() {
	*x = RemoveIpsecPortResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIpsecPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIpsecPortResponse) ProtoMessage() {}

func (x *RemoveIpsecPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIpsecPortResponse.ProtoReflect.Descriptor instead.
func (*RemoveIpsecPortResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{11}
}

type SetIpsecPortAttributeRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Oid                     uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	CtagEnable              *bool                  `protobuf:"varint,2,opt,name=ctag_enable,json=ctagEnable,proto3,oneof" json:"ctag_enable,omitempty"`
	StagEnable              *bool                  `protobuf:"varint,3,opt,name=stag_enable,json=stagEnable,proto3,oneof" json:"stag_enable,omitempty"`
	VrfFromPacketVlanEnable *bool                  `protobuf:"varint,4,opt,name=vrf_from_packet_vlan_enable,json=vrfFromPacketVlanEnable,proto3,oneof" json:"vrf_from_packet_vlan_enable,omitempty"`
	SwitchSwitchingMode     *SwitchSwitchingMode   `protobuf:"varint,5,opt,name=switch_switching_mode,json=switchSwitchingMode,proto3,enum=lemming.dataplane.sai.SwitchSwitchingMode,oneof" json:"switch_switching_mode,omitempty"`
	StatsCountMode          *StatsCountMode        `protobuf:"varint,6,opt,name=stats_count_mode,json=statsCountMode,proto3,enum=lemming.dataplane.sai.StatsCountMode,oneof" json:"stats_count_mode,omitempty"`
	SelectiveCounterList    []uint64               `protobuf:"varint,7,rep,packed,name=selective_counter_list,json=selectiveCounterList,proto3" json:"selective_counter_list,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SetIpsecPortAttributeRequest) Reset() {
	*x = SetIpsecPortAttributeRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetIpsecPortAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIpsecPortAttributeRequest) ProtoMessage() {}

func (x *SetIpsecPortAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIpsecPortAttributeRequest.ProtoReflect.Descriptor instead.
func (*SetIpsecPortAttributeRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{12}
}

func (x *SetIpsecPortAttributeRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *SetIpsecPortAttributeRequest) GetCtagEnable() bool {
	if x != nil && x.CtagEnable != nil {
		return *x.CtagEnable
	}
	return false
}

func (x *SetIpsecPortAttributeRequest) GetStagEnable() bool {
	if x != nil && x.StagEnable != nil {
		return *x.StagEnable
	}
	return false
}

func (x *SetIpsecPortAttributeRequest) GetVrfFromPacketVlanEnable() bool {
	if x != nil && x.VrfFromPacketVlanEnable != nil {
		return *x.VrfFromPacketVlanEnable
	}
	return false
}

func (x *SetIpsecPortAttributeRequest) GetSwitchSwitchingMode() SwitchSwitchingMode {
	if x != nil && x.SwitchSwitchingMode != nil {
		return *x.SwitchSwitchingMode
	}
	return SwitchSwitchingMode_SWITCH_SWITCHING_MODE_UNSPECIFIED
}

func (x *SetIpsecPortAttributeRequest) GetStatsCountMode() StatsCountMode {
	if x != nil && x.StatsCountMode != nil {
		return *x.StatsCountMode
	}
	return StatsCountMode_STATS_COUNT_MODE_UNSPECIFIED
}

func (x *SetIpsecPortAttributeRequest) GetSelectiveCounterList() []uint64 {
	if x != nil {
		return x.SelectiveCounterList
	}
	return nil
}

type SetIpsecPortAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetIpsecPortAttributeResponse) Reset() {
	*x = SetIpsecPortAttributeResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetIpsecPortAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIpsecPortAttributeResponse) ProtoMessage() {}

func (x *SetIpsecPortAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIpsecPortAttributeResponse.ProtoReflect.Descriptor instead.
func (*SetIpsecPortAttributeResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{13}
}

type GetIpsecPortAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	AttrType      []IpsecPortAttr        `protobuf:"varint,2,rep,packed,name=attr_type,json=attrType,proto3,enum=lemming.dataplane.sai.IpsecPortAttr" json:"attr_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpsecPortAttributeRequest) Reset() {
	*x = GetIpsecPortAttributeRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpsecPortAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpsecPortAttributeRequest) ProtoMessage() {}

func (x *GetIpsecPortAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpsecPortAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetIpsecPortAttributeRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{14}
}

func (x *GetIpsecPortAttributeRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *GetIpsecPortAttributeRequest) GetAttrType() []IpsecPortAttr {
	if x != nil {
		return x.AttrType
	}
	return nil
}

type GetIpsecPortAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *IpsecPortAttribute    `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpsecPortAttributeResponse) Reset() {
	*x = GetIpsecPortAttributeResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpsecPortAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpsecPortAttributeResponse) ProtoMessage() {}

func (x *GetIpsecPortAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpsecPortAttributeResponse.ProtoReflect.Descriptor instead.
func (*GetIpsecPortAttributeResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{15}
}

func (x *GetIpsecPortAttributeResponse) GetAttr() *IpsecPortAttribute {
	if x != nil {
		return x.Attr
	}
	return nil
}

type GetIpsecPortStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	CounterIds    []IpsecPortStat        `protobuf:"varint,2,rep,packed,name=counter_ids,json=counterIds,proto3,enum=lemming.dataplane.sai.IpsecPortStat" json:"counter_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpsecPortStatsRequest) Reset() {
	*x = GetIpsecPortStatsRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpsecPortStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpsecPortStatsRequest) ProtoMessage() {}

func (x *GetIpsecPortStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpsecPortStatsRequest.ProtoReflect.Descriptor instead.
func (*GetIpsecPortStatsRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{16}
}

func (x *GetIpsecPortStatsRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *GetIpsecPortStatsRequest) GetCounterIds() []IpsecPortStat {
	if x != nil {
		return x.CounterIds
	}
	return nil
}

type GetIpsecPortStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []uint64               `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpsecPortStatsResponse) Reset() {
	*x = GetIpsecPortStatsResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpsecPortStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpsecPortStatsResponse) ProtoMessage() {}

func (x *GetIpsecPortStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpsecPortStatsResponse.ProtoReflect.Descriptor instead.
func (*GetIpsecPortStatsResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{17}
}

func (x *GetIpsecPortStatsResponse) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type CreateIpsecSaRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Switch                      uint64                 `protobuf:"varint,1,opt,name=switch,proto3" json:"switch,omitempty"`
	IpsecDirection              *IpsecDirection        `protobuf:"varint,2,opt,name=ipsec_direction,json=ipsecDirection,proto3,enum=lemming.dataplane.sai.IpsecDirection,oneof" json:"ipsec_direction,omitempty"`
	IpsecId                     *uint64                `protobuf:"varint,3,opt,name=ipsec_id,json=ipsecId,proto3,oneof" json:"ipsec_id,omitempty"`
	ExternalSaIndex             *uint32                `protobuf:"varint,4,opt,name=external_sa_index,json=externalSaIndex,proto3,oneof" json:"external_sa_index,omitempty"`
	IpsecPortList               []uint64               `protobuf:"varint,5,rep,packed,name=ipsec_port_list,json=ipsecPortList,proto3" json:"ipsec_port_list,omitempty"`
	IpsecSpi                    *uint32                `protobuf:"varint,6,opt,name=ipsec_spi,json=ipsecSpi,proto3,oneof" json:"ipsec_spi,omitempty"`
	IpsecEsnEnable              *bool                  `protobuf:"varint,7,opt,name=ipsec_esn_enable,json=ipsecEsnEnable,proto3,oneof" json:"ipsec_esn_enable,omitempty"`
	IpsecCipher                 *IpsecCipher           `protobuf:"varint,8,opt,name=ipsec_cipher,json=ipsecCipher,proto3,enum=lemming.dataplane.sai.IpsecCipher,oneof" json:"ipsec_cipher,omitempty"`
	EncryptKey                  []byte                 `protobuf:"bytes,9,opt,name=encrypt_key,json=encryptKey,proto3,oneof" json:"encrypt_key,omitempty"`
	Salt                        *uint32                `protobuf:"varint,10,opt,name=salt,proto3,oneof" json:"salt,omitempty"`
	AuthKey                     []byte                 `protobuf:"bytes,11,opt,name=auth_key,json=authKey,proto3,oneof" json:"auth_key,omitempty"`
	IpsecReplayProtectionEnable *bool                  `protobuf:"varint,12,opt,name=ipsec_replay_protection_enable,json=ipsecReplayProtectionEnable,proto3,oneof" json:"ipsec_replay_protection_enable,omitempty"`
	IpsecReplayProtectionWindow *uint32                `protobuf:"varint,13,opt,name=ipsec_replay_protection_window,json=ipsecReplayProtectionWindow,proto3,oneof" json:"ipsec_replay_protection_window,omitempty"`
	TermDstIp                   []byte                 `protobuf:"bytes,14,opt,name=term_dst_ip,json=termDstIp,proto3,oneof" json:"term_dst_ip,omitempty"`
	TermVlanIdEnable            *bool                  `protobuf:"varint,15,opt,name=term_vlan_id_enable,json=termVlanIdEnable,proto3,oneof" json:"term_vlan_id_enable,omitempty"`
	TermVlanId                  *uint32                `protobuf:"varint,16,opt,name=term_vlan_id,json=termVlanId,proto3,oneof" json:"term_vlan_id,omitempty"`
	TermSrcIpEnable             *bool                  `protobuf:"varint,17,opt,name=term_src_ip_enable,json=termSrcIpEnable,proto3,oneof" json:"term_src_ip_enable,omitempty"`
	TermSrcIp                   []byte                 `protobuf:"bytes,18,opt,name=term_src_ip,json=termSrcIp,proto3,oneof" json:"term_src_ip,omitempty"`
	EgressEsn                   *uint64                `protobuf:"varint,19,opt,name=egress_esn,json=egressEsn,proto3,oneof" json:"egress_esn,omitempty"`
	MinimumIngressEsn           *uint64                `protobuf:"varint,20,opt,name=minimum_ingress_esn,json=minimumIngressEsn,proto3,oneof" json:"minimum_ingress_esn,omitempty"`
	StatsCountMode              *StatsCountMode        `protobuf:"varint,21,opt,name=stats_count_mode,json=statsCountMode,proto3,enum=lemming.dataplane.sai.StatsCountMode,oneof" json:"stats_count_mode,omitempty"`
	SelectiveCounterList        []uint64               `protobuf:"varint,22,rep,packed,name=selective_counter_list,json=selectiveCounterList,proto3" json:"selective_counter_list,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CreateIpsecSaRequest) Reset() {
	*x = CreateIpsecSaRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIpsecSaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIpsecSaRequest) ProtoMessage() {}

func (x *CreateIpsecSaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIpsecSaRequest.ProtoReflect.Descriptor instead.
func (*CreateIpsecSaRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{18}
}

func (x *CreateIpsecSaRequest) GetSwitch() uint64 {
	if x != nil {
		return x.Switch
	}
	return 0
}

func (x *CreateIpsecSaRequest) GetIpsecDirection() IpsecDirection {
	if x != nil && x.IpsecDirection != nil {
		return *x.IpsecDirection
	}
	return IpsecDirection_IPSEC_DIRECTION_UNSPECIFIED
}

func (x *CreateIpsecSaRequest) GetIpsecId() uint64 {
	if x != nil && x.IpsecId != nil {
		return *x.IpsecId
	}
	return 0
}

func (x *CreateIpsecSaRequest) GetExternalSaIndex() uint32 {
	if x != nil && x.ExternalSaIndex != nil {
		return *x.ExternalSaIndex
	}
	return 0
}

func (x *CreateIpsecSaRequest) GetIpsecPortList() []uint64 {
	if x != nil {
		return x.IpsecPortList
	}
	return nil
}

func (x *CreateIpsecSaRequest) GetIpsecSpi() uint32 {
	if x != nil && x.IpsecSpi != nil {
		return *x.IpsecSpi
	}
	return 0
}

func (x *CreateIpsecSaRequest) GetIpsecEsnEnable() bool {
	if x != nil && x.IpsecEsnEnable != nil {
		return *x.IpsecEsnEnable
	}
	return false
}

func (x *CreateIpsecSaRequest) GetIpsecCipher() IpsecCipher {
	if x != nil && x.IpsecCipher != nil {
		return *x.IpsecCipher
	}
	return IpsecCipher_IPSEC_CIPHER_UNSPECIFIED
}

func (x *CreateIpsecSaRequest) GetEncryptKey() []byte {
	if x != nil {
		return x.EncryptKey
	}
	return nil
}

func (x *CreateIpsecSaRequest) GetSalt() uint32 {
	if x != nil && x.Salt != nil {
		return *x.Salt
	}
	return 0
}

func (x *CreateIpsecSaRequest) GetAuthKey() []byte {
	if x != nil {
		return x.AuthKey
	}
	return nil
}

func (x *CreateIpsecSaRequest) GetIpsecReplayProtectionEnable() bool {
	if x != nil && x.IpsecReplayProtectionEnable != nil {
		return *x.IpsecReplayProtectionEnable
	}
	return false
}

func (x *CreateIpsecSaRequest) GetIpsecReplayProtectionWindow() uint32 {
	if x != nil && x.IpsecReplayProtectionWindow != nil {
		return *x.IpsecReplayProtectionWindow
	}
	return 0
}

func (x *CreateIpsecSaRequest) GetTermDstIp() []byte {
	if x != nil {
		return x.TermDstIp
	}
	return nil
}

func (x *CreateIpsecSaRequest) GetTermVlanIdEnable() bool {
	if x != nil && x.TermVlanIdEnable != nil {
		return *x.TermVlanIdEnable
	}
	return false
}

func (x *CreateIpsecSaRequest) GetTermVlanId() uint32 {
	if x != nil && x.TermVlanId != nil {
		return *x.TermVlanId
	}
	return 0
}

func (x *CreateIpsecSaRequest) GetTermSrcIpEnable() bool {
	if x != nil && x.TermSrcIpEnable != nil {
		return *x.TermSrcIpEnable
	}
	return false
}

func (x *CreateIpsecSaRequest) GetTermSrcIp() []byte {
	if x != nil {
		return x.TermSrcIp
	}
	return nil
}

func (x *CreateIpsecSaRequest) GetEgressEsn() uint64 {
	if x != nil && x.EgressEsn != nil {
		return *x.EgressEsn
	}
	return 0
}

func (x *CreateIpsecSaRequest) GetMinimumIngressEsn() uint64 {
	if x != nil && x.MinimumIngressEsn != nil {
		return *x.MinimumIngressEsn
	}
	return 0
}

func (x *CreateIpsecSaRequest) GetStatsCountMode() StatsCountMode {
	if x != nil && x.StatsCountMode != nil {
		return *x.StatsCountMode
	}
	return StatsCountMode_STATS_COUNT_MODE_UNSPECIFIED
}

func (x *CreateIpsecSaRequest) GetSelectiveCounterList() []uint64 {
	if x != nil {
		return x.SelectiveCounterList
	}
	return nil
}

type CreateIpsecSaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIpsecSaResponse) Reset() {
	*x = CreateIpsecSaResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIpsecSaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIpsecSaResponse) ProtoMessage() {}

func (x *CreateIpsecSaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIpsecSaResponse.ProtoReflect.Descriptor instead.
func (*CreateIpsecSaResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{19}
}

func (x *CreateIpsecSaResponse) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveIpsecSaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIpsecSaRequest) Reset() {
	*x = RemoveIpsecSaRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIpsecSaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIpsecSaRequest) ProtoMessage() {}

func (x *RemoveIpsecSaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIpsecSaRequest.ProtoReflect.Descriptor instead.
func (*RemoveIpsecSaRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveIpsecSaRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveIpsecSaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIpsecSaResponse) Reset() {
	*x = RemoveIpsecSaResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIpsecSaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIpsecSaResponse) ProtoMessage() {}

func (x *RemoveIpsecSaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIpsecSaResponse.ProtoReflect.Descriptor instead.
func (*RemoveIpsecSaResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{21}
}

type SetIpsecSaAttributeRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Oid                         uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	ExternalSaIndex             *uint32                `protobuf:"varint,2,opt,name=external_sa_index,json=externalSaIndex,proto3,oneof" json:"external_sa_index,omitempty"`
	IpsecPortList               []uint64               `protobuf:"varint,3,rep,packed,name=ipsec_port_list,json=ipsecPortList,proto3" json:"ipsec_port_list,omitempty"`
	IpsecReplayProtectionEnable *bool                  `protobuf:"varint,4,opt,name=ipsec_replay_protection_enable,json=ipsecReplayProtectionEnable,proto3,oneof" json:"ipsec_replay_protection_enable,omitempty"`
	IpsecReplayProtectionWindow *uint32                `protobuf:"varint,5,opt,name=ipsec_replay_protection_window,json=ipsecReplayProtectionWindow,proto3,oneof" json:"ipsec_replay_protection_window,omitempty"`
	EgressEsn                   *uint64                `protobuf:"varint,6,opt,name=egress_esn,json=egressEsn,proto3,oneof" json:"egress_esn,omitempty"`
	MinimumIngressEsn           *uint64                `protobuf:"varint,7,opt,name=minimum_ingress_esn,json=minimumIngressEsn,proto3,oneof" json:"minimum_ingress_esn,omitempty"`
	StatsCountMode              *StatsCountMode        `protobuf:"varint,8,opt,name=stats_count_mode,json=statsCountMode,proto3,enum=lemming.dataplane.sai.StatsCountMode,oneof" json:"stats_count_mode,omitempty"`
	SelectiveCounterList        []uint64               `protobuf:"varint,9,rep,packed,name=selective_counter_list,json=selectiveCounterList,proto3" json:"selective_counter_list,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SetIpsecSaAttributeRequest) Reset() {
	*x = SetIpsecSaAttributeRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetIpsecSaAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIpsecSaAttributeRequest) ProtoMessage() {}

func (x *SetIpsecSaAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIpsecSaAttributeRequest.ProtoReflect.Descriptor instead.
func (*SetIpsecSaAttributeRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{22}
}

func (x *SetIpsecSaAttributeRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *SetIpsecSaAttributeRequest) GetExternalSaIndex() uint32 {
	if x != nil && x.ExternalSaIndex != nil {
		return *x.ExternalSaIndex
	}
	return 0
}

func (x *SetIpsecSaAttributeRequest) GetIpsecPortList() []uint64 {
	if x != nil {
		return x.IpsecPortList
	}
	return nil
}

func (x *SetIpsecSaAttributeRequest) GetIpsecReplayProtectionEnable() bool {
	if x != nil && x.IpsecReplayProtectionEnable != nil {
		return *x.IpsecReplayProtectionEnable
	}
	return false
}

func (x *SetIpsecSaAttributeRequest) GetIpsecReplayProtectionWindow() uint32 {
	if x != nil && x.IpsecReplayProtectionWindow != nil {
		return *x.IpsecReplayProtectionWindow
	}
	return 0
}

func (x *SetIpsecSaAttributeRequest) GetEgressEsn() uint64 {
	if x != nil && x.EgressEsn != nil {
		return *x.EgressEsn
	}
	return 0
}

func (x *SetIpsecSaAttributeRequest) GetMinimumIngressEsn() uint64 {
	if x != nil && x.MinimumIngressEsn != nil {
		return *x.MinimumIngressEsn
	}
	return 0
}

func (x *SetIpsecSaAttributeRequest) GetStatsCountMode() StatsCountMode {
	if x != nil && x.StatsCountMode != nil {
		return *x.StatsCountMode
	}
	return StatsCountMode_STATS_COUNT_MODE_UNSPECIFIED
}

func (x *SetIpsecSaAttributeRequest) GetSelectiveCounterList() []uint64 {
	if x != nil {
		return x.SelectiveCounterList
	}
	return nil
}

type SetIpsecSaAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetIpsecSaAttributeResponse) Reset() {
	*x = SetIpsecSaAttributeResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetIpsecSaAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIpsecSaAttributeResponse) ProtoMessage() {}

func (x *SetIpsecSaAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIpsecSaAttributeResponse.ProtoReflect.Descriptor instead.
func (*SetIpsecSaAttributeResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{23}
}

type GetIpsecSaAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	AttrType      []IpsecSaAttr          `protobuf:"varint,2,rep,packed,name=attr_type,json=attrType,proto3,enum=lemming.dataplane.sai.IpsecSaAttr" json:"attr_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpsecSaAttributeRequest) Reset() {
	*x = GetIpsecSaAttributeRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpsecSaAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpsecSaAttributeRequest) ProtoMessage() {}

func (x *GetIpsecSaAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpsecSaAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetIpsecSaAttributeRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{24}
}

func (x *GetIpsecSaAttributeRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *GetIpsecSaAttributeRequest) GetAttrType() []IpsecSaAttr {
	if x != nil {
		return x.AttrType
	}
	return nil
}

type GetIpsecSaAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *IpsecSaAttribute      `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpsecSaAttributeResponse) Reset() {
	*x = GetIpsecSaAttributeResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpsecSaAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpsecSaAttributeResponse) ProtoMessage() {}

func (x *GetIpsecSaAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpsecSaAttributeResponse.ProtoReflect.Descriptor instead.
func (*GetIpsecSaAttributeResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{25}
}

func (x *GetIpsecSaAttributeResponse) GetAttr() *IpsecSaAttribute {
	if x != nil {
		return x.Attr
	}
	return nil
}

type GetIpsecSaStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	CounterIds    []IpsecSaStat          `protobuf:"varint,2,rep,packed,name=counter_ids,json=counterIds,proto3,enum=lemming.dataplane.sai.IpsecSaStat" json:"counter_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpsecSaStatsRequest) Reset() {
	*x = GetIpsecSaStatsRequest{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpsecSaStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpsecSaStatsRequest) ProtoMessage() {}

func (x *GetIpsecSaStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpsecSaStatsRequest.ProtoReflect.Descriptor instead.
func (*GetIpsecSaStatsRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{26}
}

func (x *GetIpsecSaStatsRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *GetIpsecSaStatsRequest) GetCounterIds() []IpsecSaStat {
	if x != nil {
		return x.CounterIds
	}
	return nil
}

type GetIpsecSaStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []uint64               `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpsecSaStatsResponse) Reset() {
	*x = GetIpsecSaStatsResponse{}
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpsecSaStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpsecSaStatsResponse) ProtoMessage() {}

func (x *GetIpsecSaStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_ipsec_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpsecSaStatsResponse.ProtoReflect.Descriptor instead.
func (*GetIpsecSaStatsResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_ipsec_proto_rawDescGZIP(), []int{27}
}

func (x *GetIpsecSaStatsResponse) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_dataplane_proto_sai_ipsec_proto protoreflect.FileDescriptor

const file_dataplane_proto_sai_ipsec_proto_rawDesc = "" +
	"\n" +
	"\x1fdataplane/proto/sai/ipsec.proto\x12\x15lemming.dataplane.sai\x1a dataplane/proto/sai/common.proto\"\xd6\x05\n" +
	"\x12CreateIpsecRequest\x12\x16\n" +
	"\x06switch\x18\x01 \x01(\x04R\x06switch\x125\n" +
	"\x10warm_boot_enable\x18\x02 \x01(\bB\x06\xf0ܓ\xad\x0f\vH\x00R\x0ewarmBootEnable\x88\x01\x01\x12D\n" +
	"\x18external_sa_index_enable\x18\x03 \x01(\bB\x06\xf0ܓ\xad\x0f\fH\x01R\x15externalSaIndexEnable\x88\x01\x01\x12(\n" +
	"\tctag_tpid\x18\x04 \x01(\rB\x06\xf0ܓ\xad\x0f\rH\x02R\bctagTpid\x88\x01\x01\x12(\n" +
	"\tstag_tpid\x18\x05 \x01(\rB\x06\xf0ܓ\xad\x0f\x0eH\x03R\bstagTpid\x88\x01\x01\x12<\n" +
	"\x14max_vlan_tags_parsed\x18\x06 \x01(\rB\x06\xf0ܓ\xad\x0f\x0fH\x04R\x11maxVlanTagsParsed\x88\x01\x01\x12H\n" +
	"\x1aoctet_count_high_watermark\x18\a \x01(\x04B\x06\xf0ܓ\xad\x0f\x10H\x05R\x17octetCountHighWatermark\x88\x01\x01\x12F\n" +
	"\x19octet_count_low_watermark\x18\b \x01(\x04B\x06\xf0ܓ\xad\x0f\x11H\x06R\x16octetCountLowWatermark\x88\x01\x01\x12L\n" +
	"\n" +
	"stats_mode\x18\t \x01(\x0e2 .lemming.dataplane.sai.StatsModeB\x06\xf0ܓ\xad\x0f\x12H\aR\tstatsMode\x88\x01\x01:\x06\xa0\xa9\x90\xad\x0fdB\x13\n" +
	"\x11_warm_boot_enableB\x1b\n" +
	"\x19_external_sa_index_enableB\f\n" +
	"\n" +
	"_ctag_tpidB\f\n" +
	"\n" +
	"_stag_tpidB\x17\n" +
	"\x15_max_vlan_tags_parsedB\x1d\n" +
	"\x1b_octet_count_high_watermarkB\x1c\n" +
	"\x1a_octet_count_low_watermarkB\r\n" +
	"\v_stats_mode\"'\n" +
	"\x13CreateIpsecResponse\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\"&\n" +
	"\x12RemoveIpsecRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\"\x15\n" +
	"\x13RemoveIpsecResponse\"\xeb\x04\n" +
	"\x18SetIpsecAttributeRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\x125\n" +
	"\x10warm_boot_enable\x18\x02 \x01(\bB\x06\xf0ܓ\xad\x0f\vH\x00R\x0ewarmBootEnable\x88\x01\x01\x12(\n" +
	"\tctag_tpid\x18\x03 \x01(\rB\x06\xf0ܓ\xad\x0f\rH\x01R\bctagTpid\x88\x01\x01\x12(\n" +
	"\tstag_tpid\x18\x04 \x01(\rB\x06\xf0ܓ\xad\x0f\x0eH\x02R\bstagTpid\x88\x01\x01\x12<\n" +
	"\x14max_vlan_tags_parsed\x18\x05 \x01(\rB\x06\xf0ܓ\xad\x0f\x0fH\x03R\x11maxVlanTagsParsed\x88\x01\x01\x12H\n" +
	"\x1aoctet_count_high_watermark\x18\x06 \x01(\x04B\x06\xf0ܓ\xad\x0f\x10H\x04R\x17octetCountHighWatermark\x88\x01\x01\x12F\n" +
	"\x19octet_count_low_watermark\x18\a \x01(\x04B\x06\xf0ܓ\xad\x0f\x11H\x05R\x16octetCountLowWatermark\x88\x01\x01\x12L\n" +
	"\n" +
	"stats_mode\x18\b \x01(\x0e2 .lemming.dataplane.sai.StatsModeB\x06\xf0ܓ\xad\x0f\x12H\x06R\tstatsMode\x88\x01\x01B\x13\n" +
	"\x11_warm_boot_enableB\f\n" +
	"\n" +
	"_ctag_tpidB\f\n" +
	"\n" +
	"_stag_tpidB\x17\n" +
	"\x15_max_vlan_tags_parsedB\x1d\n" +
	"\x1b_octet_count_high_watermarkB\x1c\n" +
	"\x1a_octet_count_low_watermarkB\r\n" +
	"\v_stats_mode\"\x1b\n" +
	"\x19SetIpsecAttributeResponse\"k\n" +
	"\x18GetIpsecAttributeRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\x12=\n" +
	"\tattr_type\x18\x02 \x03(\x0e2 .lemming.dataplane.sai.IpsecAttrR\battrType\"V\n" +
	"\x19GetIpsecAttributeResponse\x129\n" +
	"\x04attr\x18\x01 \x01(\v2%.lemming.dataplane.sai.IpsecAttributeR\x04attr\"\xcf\x05\n" +
	"\x16CreateIpsecPortRequest\x12\x16\n" +
	"\x06switch\x18\x01 \x01(\x04R\x06switch\x12$\n" +
	"\aport_id\x18\x02 \x01(\x04B\x06\xf0ܓ\xad\x0f\x01H\x00R\x06portId\x88\x01\x01\x12,\n" +
	"\vctag_enable\x18\x03 \x01(\bB\x06\xf0ܓ\xad\x0f\x02H\x01R\n" +
	"ctagEnable\x88\x01\x01\x12,\n" +
	"\vstag_enable\x18\x04 \x01(\bB\x06\xf0ܓ\xad\x0f\x03H\x02R\n" +
	"stagEnable\x88\x01\x01\x121\n" +
	"\x0enative_vlan_id\x18\x05 \x01(\rB\x06\xf0ܓ\xad\x0f\x04H\x03R\fnativeVlanId\x88\x01\x01\x12I\n" +
	"\x1bvrf_from_packet_vlan_enable\x18\x06 \x01(\bB\x06\xf0ܓ\xad\x0f\x05H\x04R\x17vrfFromPacketVlanEnable\x88\x01\x01\x12k\n" +
	"\x15switch_switching_mode\x18\a \x01(\x0e2*.lemming.dataplane.sai.SwitchSwitchingModeB\x06\xf0ܓ\xad\x0f\x06H\x05R\x13switchSwitchingMode\x88\x01\x01\x12\\\n" +
	"\x10stats_count_mode\x18\b \x01(\x0e2%.lemming.dataplane.sai.StatsCountModeB\x06\xf0ܓ\xad\x0f\aH\x06R\x0estatsCountMode\x88\x01\x01\x12<\n" +
	"\x16selective_counter_list\x18\t \x03(\x04B\x06\xf0ܓ\xad\x0f\bR\x14selectiveCounterList:\x06\xa0\xa9\x90\xad\x0feB\n" +
	"\n" +
	"\b_port_idB\x0e\n" +
	"\f_ctag_enableB\x0e\n" +
	"\f_stag_enableB\x11\n" +
	"\x0f_native_vlan_idB\x1e\n" +
	"\x1c_vrf_from_packet_vlan_enableB\x18\n" +
	"\x16_switch_switching_modeB\x13\n" +
	"\x11_stats_count_mode\"+\n" +
	"\x17CreateIpsecPortResponse\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\"*\n" +
	"\x16RemoveIpsecPortRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\"\x19\n" +
	"\x17RemoveIpsecPortResponse\"\xcf\x04\n" +
	"\x1cSetIpsecPortAttributeRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\x12,\n" +
	"\vctag_enable\x18\x02 \x01(\bB\x06\xf0ܓ\xad\x0f\x02H\x00R\n" +
	"ctagEnable\x88\x01\x01\x12,\n" +
	"\vstag_enable\x18\x03 \x01(\bB\x06\xf0ܓ\xad\x0f\x03H\x01R\n" +
	"stagEnable\x88\x01\x01\x12I\n" +
	"\x1bvrf_from_packet_vlan_enable\x18\x04 \x01(\bB\x06\xf0ܓ\xad\x0f\x05H\x02R\x17vrfFromPacketVlanEnable\x88\x01\x01\x12k\n" +
	"\x15switch_switching_mode\x18\x05 \x01(\x0e2*.lemming.dataplane.sai.SwitchSwitchingModeB\x06\xf0ܓ\xad\x0f\x06H\x03R\x13switchSwitchingMode\x88\x01\x01\x12\\\n" +
	"\x10stats_count_mode\x18\x06 \x01(\x0e2%.lemming.dataplane.sai.StatsCountModeB\x06\xf0ܓ\xad\x0f\aH\x04R\x0estatsCountMode\x88\x01\x01\x12<\n" +
	"\x16selective_counter_list\x18\a \x03(\x04B\x06\xf0ܓ\xad\x0f\bR\x14selectiveCounterListB\x0e\n" +
	"\f_ctag_enableB\x0e\n" +
	"\f_stag_enableB\x1e\n" +
	"\x1c_vrf_from_packet_vlan_enableB\x18\n" +
	"\x16_switch_switching_modeB\x13\n" +
	"\x11_stats_count_mode\"\x1f\n" +
	"\x1dSetIpsecPortAttributeResponse\"s\n" +
	"\x1cGetIpsecPortAttributeRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\x12A\n" +
	"\tattr_type\x18\x02 \x03(\x0e2$.lemming.dataplane.sai.IpsecPortAttrR\battrType\"^\n" +
	"\x1dGetIpsecPortAttributeResponse\x12=\n" +
	"\x04attr\x18\x01 \x01(\v2).lemming.dataplane.sai.IpsecPortAttributeR\x04attr\"s\n" +
	"\x18GetIpsecPortStatsRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\x12E\n" +
	"\vcounter_ids\x18\x02 \x03(\x0e2$.lemming.dataplane.sai.IpsecPortStatR\n" +
	"counterIds\"3\n" +
	"\x19GetIpsecPortStatsResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x04R\x06values\"\xeb\f\n" +
	"\x14CreateIpsecSaRequest\x12\x16\n" +
	"\x06switch\x18\x01 \x01(\x04R\x06switch\x12[\n" +
	"\x0fipsec_direction\x18\x02 \x01(\x0e2%.lemming.dataplane.sai.IpsecDirectionB\x06\xf0ܓ\xad\x0f\x01H\x00R\x0eipsecDirection\x88\x01\x01\x12&\n" +
	"\bipsec_id\x18\x03 \x01(\x04B\x06\xf0ܓ\xad\x0f\x02H\x01R\aipsecId\x88\x01\x01\x127\n" +
	"\x11external_sa_index\x18\x04 \x01(\rB\x06\xf0ܓ\xad\x0f\x04H\x02R\x0fexternalSaIndex\x88\x01\x01\x12.\n" +
	"\x0fipsec_port_list\x18\x05 \x03(\x04B\x06\xf0ܓ\xad\x0f\x06R\ripsecPortList\x12(\n" +
	"\tipsec_spi\x18\x06 \x01(\rB\x06\xf0ܓ\xad\x0f\aH\x03R\bipsecSpi\x88\x01\x01\x125\n" +
	"\x10ipsec_esn_enable\x18\a \x01(\bB\x06\xf0ܓ\xad\x0f\bH\x04R\x0eipsecEsnEnable\x88\x01\x01\x12R\n" +
	"\fipsec_cipher\x18\b \x01(\x0e2\".lemming.dataplane.sai.IpsecCipherB\x06\xf0ܓ\xad\x0f\tH\x05R\vipsecCipher\x88\x01\x01\x12,\n" +
	"\vencrypt_key\x18\t \x01(\fB\x06\xf0ܓ\xad\x0f\n" +
	"H\x06R\n" +
	"encryptKey\x88\x01\x01\x12\x1f\n" +
	"\x04salt\x18\n" +
	" \x01(\rB\x06\xf0ܓ\xad\x0f\vH\aR\x04salt\x88\x01\x01\x12&\n" +
	"\bauth_key\x18\v \x01(\fB\x06\xf0ܓ\xad\x0f\fH\bR\aauthKey\x88\x01\x01\x12P\n" +
	"\x1eipsec_replay_protection_enable\x18\f \x01(\bB\x06\xf0ܓ\xad\x0f\rH\tR\x1bipsecReplayProtectionEnable\x88\x01\x01\x12P\n" +
	"\x1eipsec_replay_protection_window\x18\r \x01(\rB\x06\xf0ܓ\xad\x0f\x0eH\n" +
	"R\x1bipsecReplayProtectionWindow\x88\x01\x01\x12+\n" +
	"\vterm_dst_ip\x18\x0e \x01(\fB\x06\xf0ܓ\xad\x0f\x0fH\vR\ttermDstIp\x88\x01\x01\x12:\n" +
	"\x13term_vlan_id_enable\x18\x0f \x01(\bB\x06\xf0ܓ\xad\x0f\x10H\fR\x10termVlanIdEnable\x88\x01\x01\x12-\n" +
	"\fterm_vlan_id\x18\x10 \x01(\rB\x06\xf0ܓ\xad\x0f\x11H\rR\n" +
	"termVlanId\x88\x01\x01\x128\n" +
	"\x12term_src_ip_enable\x18\x11 \x01(\bB\x06\xf0ܓ\xad\x0f\x12H\x0eR\x0ftermSrcIpEnable\x88\x01\x01\x12+\n" +
	"\vterm_src_ip\x18\x12 \x01(\fB\x06\xf0ܓ\xad\x0f\x13H\x0fR\ttermSrcIp\x88\x01\x01\x12*\n" +
	"\n" +
	"egress_esn\x18\x13 \x01(\x04B\x06\xf0ܓ\xad\x0f\x14H\x10R\tegressEsn\x88\x01\x01\x12;\n" +
	"\x13minimum_ingress_esn\x18\x14 \x01(\x04B\x06\xf0ܓ\xad\x0f\x15H\x11R\x11minimumIngressEsn\x88\x01\x01\x12\\\n" +
	"\x10stats_count_mode\x18\x15 \x01(\x0e2%.lemming.dataplane.sai.StatsCountModeB\x06\xf0ܓ\xad\x0f\x16H\x12R\x0estatsCountMode\x88\x01\x01\x12<\n" +
	"\x16selective_counter_list\x18\x16 \x03(\x04B\x06\xf0ܓ\xad\x0f\x17R\x14selectiveCounterList:\x06\xa0\xa9\x90\xad\x0ffB\x12\n" +
	"\x10_ipsec_directionB\v\n" +
	"\t_ipsec_idB\x14\n" +
	"\x12_external_sa_indexB\f\n" +
	"\n" +
	"_ipsec_spiB\x13\n" +
	"\x11_ipsec_esn_enableB\x0f\n" +
	"\r_ipsec_cipherB\x0e\n" +
	"\f_encrypt_keyB\a\n" +
	"\x05_saltB\v\n" +
	"\t_auth_keyB!\n" +
	"\x1f_ipsec_replay_protection_enableB!\n" +
	"\x1f_ipsec_replay_protection_windowB\x0e\n" +
	"\f_term_dst_ipB\x16\n" +
	"\x14_term_vlan_id_enableB\x0f\n" +
	"\r_term_vlan_idB\x15\n" +
	"\x13_term_src_ip_enableB\x0e\n" +
	"\f_term_src_ipB\r\n" +
	"\v_egress_esnB\x16\n" +
	"\x14_minimum_ingress_esnB\x13\n" +
	"\x11_stats_count_mode\")\n" +
	"\x15CreateIpsecSaResponse\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\"(\n" +
	"\x14RemoveIpsecSaRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\"\x17\n" +
	"\x15RemoveIpsecSaResponse\"\xd8\x05\n" +
	"\x1aSetIpsecSaAttributeRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\x127\n" +
	"\x11external_sa_index\x18\x02 \x01(\rB\x06\xf0ܓ\xad\x0f\x04H\x00R\x0fexternalSaIndex\x88\x01\x01\x12.\n" +
	"\x0fipsec_port_list\x18\x03 \x03(\x04B\x06\xf0ܓ\xad\x0f\x06R\ripsecPortList\x12P\n" +
	"\x1eipsec_replay_protection_enable\x18\x04 \x01(\bB\x06\xf0ܓ\xad\x0f\rH\x01R\x1bipsecReplayProtectionEnable\x88\x01\x01\x12P\n" +
	"\x1eipsec_replay_protection_window\x18\x05 \x01(\rB\x06\xf0ܓ\xad\x0f\x0eH\x02R\x1bipsecReplayProtectionWindow\x88\x01\x01\x12*\n" +
	"\n" +
	"egress_esn\x18\x06 \x01(\x04B\x06\xf0ܓ\xad\x0f\x14H\x03R\tegressEsn\x88\x01\x01\x12;\n" +
	"\x13minimum_ingress_esn\x18\a \x01(\x04B\x06\xf0ܓ\xad\x0f\x15H\x04R\x11minimumIngressEsn\x88\x01\x01\x12\\\n" +
	"\x10stats_count_mode\x18\b \x01(\x0e2%.lemming.dataplane.sai.StatsCountModeB\x06\xf0ܓ\xad\x0f\x16H\x05R\x0estatsCountMode\x88\x01\x01\x12<\n" +
	"\x16selective_counter_list\x18\t \x03(\x04B\x06\xf0ܓ\xad\x0f\x17R\x14selectiveCounterListB\x14\n" +
	"\x12_external_sa_indexB!\n" +
	"\x1f_ipsec_replay_protection_enableB!\n" +
	"\x1f_ipsec_replay_protection_windowB\r\n" +
	"\v_egress_esnB\x16\n" +
	"\x14_minimum_ingress_esnB\x13\n" +
	"\x11_stats_count_mode\"\x1d\n" +
	"\x1bSetIpsecSaAttributeResponse\"o\n" +
	"\x1aGetIpsecSaAttributeRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\x12?\n" +
	"\tattr_type\x18\x02 \x03(\x0e2\".lemming.dataplane.sai.IpsecSaAttrR\battrType\"Z\n" +
	"\x1bGetIpsecSaAttributeResponse\x12;\n" +
	"\x04attr\x18\x01 \x01(\v2'.lemming.dataplane.sai.IpsecSaAttributeR\x04attr\"o\n" +
	"\x16GetIpsecSaStatsRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\x12C\n" +
	"\vcounter_ids\x18\x02 \x03(\x0e2\".lemming.dataplane.sai.IpsecSaStatR\n" +
	"counterIds\"1\n" +
	"\x17GetIpsecSaStatsResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x04R\x06values*\x9f\x06\n" +
	"\tIpsecAttr\x12\x1a\n" +
	"\x16IPSEC_ATTR_UNSPECIFIED\x10\x00\x12-\n" +
	")IPSEC_ATTR_TERM_REMOTE_IP_MATCH_SUPPORTED\x10\x01\x123\n" +
	"/IPSEC_ATTR_SWITCHING_MODE_CUT_THROUGH_SUPPORTED\x10\x02\x129\n" +
	"5IPSEC_ATTR_SWITCHING_MODE_STORE_AND_FORWARD_SUPPORTED\x10\x03\x12(\n" +
	"$IPSEC_ATTR_STATS_MODE_READ_SUPPORTED\x10\x04\x12.\n" +
	"*IPSEC_ATTR_STATS_MODE_READ_CLEAR_SUPPORTED\x10\x05\x12!\n" +
	"\x1dIPSEC_ATTR_SN_32BIT_SUPPORTED\x10\x06\x12\"\n" +
	"\x1eIPSEC_ATTR_ESN_64BIT_SUPPORTED\x10\a\x12$\n" +
	" IPSEC_ATTR_SUPPORTED_CIPHER_LIST\x10\b\x12\x1e\n" +
	"\x1aIPSEC_ATTR_SYSTEM_SIDE_MTU\x10\t\x12\"\n" +
	"\x1eIPSEC_ATTR_WARM_BOOT_SUPPORTED\x10\n" +
	"\x12\x1f\n" +
	"\x1bIPSEC_ATTR_WARM_BOOT_ENABLE\x10\v\x12'\n" +
	"#IPSEC_ATTR_EXTERNAL_SA_INDEX_ENABLE\x10\f\x12\x18\n" +
	"\x14IPSEC_ATTR_CTAG_TPID\x10\r\x12\x18\n" +
	"\x14IPSEC_ATTR_STAG_TPID\x10\x0e\x12#\n" +
	"\x1fIPSEC_ATTR_MAX_VLAN_TAGS_PARSED\x10\x0f\x12)\n" +
	"%IPSEC_ATTR_OCTET_COUNT_HIGH_WATERMARK\x10\x10\x12(\n" +
	"$IPSEC_ATTR_OCTET_COUNT_LOW_WATERMARK\x10\x11\x12\x19\n" +
	"\x15IPSEC_ATTR_STATS_MODE\x10\x12\x12!\n" +
	"\x1dIPSEC_ATTR_AVAILABLE_IPSEC_SA\x10\x13\x12\x16\n" +
	"\x12IPSEC_ATTR_SA_LIST\x10\x14*\xe1\x02\n" +
	"\rIpsecPortAttr\x12\x1f\n" +
	"\x1bIPSEC_PORT_ATTR_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17IPSEC_PORT_ATTR_PORT_ID\x10\x01\x12\x1f\n" +
	"\x1bIPSEC_PORT_ATTR_CTAG_ENABLE\x10\x02\x12\x1f\n" +
	"\x1bIPSEC_PORT_ATTR_STAG_ENABLE\x10\x03\x12\"\n" +
	"\x1eIPSEC_PORT_ATTR_NATIVE_VLAN_ID\x10\x04\x12/\n" +
	"+IPSEC_PORT_ATTR_VRF_FROM_PACKET_VLAN_ENABLE\x10\x05\x12)\n" +
	"%IPSEC_PORT_ATTR_SWITCH_SWITCHING_MODE\x10\x06\x12$\n" +
	" IPSEC_PORT_ATTR_STATS_COUNT_MODE\x10\a\x12*\n" +
	"&IPSEC_PORT_ATTR_SELECTIVE_COUNTER_LIST\x10\b*\xcb\x06\n" +
	"\vIpsecSaAttr\x12\x1d\n" +
	"\x19IPSEC_SA_ATTR_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dIPSEC_SA_ATTR_IPSEC_DIRECTION\x10\x01\x12\x1a\n" +
	"\x16IPSEC_SA_ATTR_IPSEC_ID\x10\x02\x12$\n" +
	" IPSEC_SA_ATTR_OCTET_COUNT_STATUS\x10\x03\x12#\n" +
	"\x1fIPSEC_SA_ATTR_EXTERNAL_SA_INDEX\x10\x04\x12\x1a\n" +
	"\x16IPSEC_SA_ATTR_SA_INDEX\x10\x05\x12!\n" +
	"\x1dIPSEC_SA_ATTR_IPSEC_PORT_LIST\x10\x06\x12\x1b\n" +
	"\x17IPSEC_SA_ATTR_IPSEC_SPI\x10\a\x12\"\n" +
	"\x1eIPSEC_SA_ATTR_IPSEC_ESN_ENABLE\x10\b\x12\x1e\n" +
	"\x1aIPSEC_SA_ATTR_IPSEC_CIPHER\x10\t\x12\x1d\n" +
	"\x19IPSEC_SA_ATTR_ENCRYPT_KEY\x10\n" +
	"\x12\x16\n" +
	"\x12IPSEC_SA_ATTR_SALT\x10\v\x12\x1a\n" +
	"\x16IPSEC_SA_ATTR_AUTH_KEY\x10\f\x120\n" +
	",IPSEC_SA_ATTR_IPSEC_REPLAY_PROTECTION_ENABLE\x10\r\x120\n" +
	",IPSEC_SA_ATTR_IPSEC_REPLAY_PROTECTION_WINDOW\x10\x0e\x12\x1d\n" +
	"\x19IPSEC_SA_ATTR_TERM_DST_IP\x10\x0f\x12%\n" +
	"!IPSEC_SA_ATTR_TERM_VLAN_ID_ENABLE\x10\x10\x12\x1e\n" +
	"\x1aIPSEC_SA_ATTR_TERM_VLAN_ID\x10\x11\x12$\n" +
	" IPSEC_SA_ATTR_TERM_SRC_IP_ENABLE\x10\x12\x12\x1d\n" +
	"\x19IPSEC_SA_ATTR_TERM_SRC_IP\x10\x13\x12\x1c\n" +
	"\x18IPSEC_SA_ATTR_EGRESS_ESN\x10\x14\x12%\n" +
	"!IPSEC_SA_ATTR_MINIMUM_INGRESS_ESN\x10\x15\x12\"\n" +
	"\x1eIPSEC_SA_ATTR_STATS_COUNT_MODE\x10\x16\x12(\n" +
	"$IPSEC_SA_ATTR_SELECTIVE_COUNTER_LIST\x10\x172\x8b\r\n" +
	"\x05Ipsec\x12f\n" +
	"\vCreateIpsec\x12).lemming.dataplane.sai.CreateIpsecRequest\x1a*.lemming.dataplane.sai.CreateIpsecResponse\"\x00\x12f\n" +
	"\vRemoveIpsec\x12).lemming.dataplane.sai.RemoveIpsecRequest\x1a*.lemming.dataplane.sai.RemoveIpsecResponse\"\x00\x12x\n" +
	"\x11SetIpsecAttribute\x12/.lemming.dataplane.sai.SetIpsecAttributeRequest\x1a0.lemming.dataplane.sai.SetIpsecAttributeResponse\"\x00\x12x\n" +
	"\x11GetIpsecAttribute\x12/.lemming.dataplane.sai.GetIpsecAttributeRequest\x1a0.lemming.dataplane.sai.GetIpsecAttributeResponse\"\x00\x12r\n" +
	"\x0fCreateIpsecPort\x12-.lemming.dataplane.sai.CreateIpsecPortRequest\x1a..lemming.dataplane.sai.CreateIpsecPortResponse\"\x00\x12r\n" +
	"\x0fRemoveIpsecPort\x12-.lemming.dataplane.sai.RemoveIpsecPortRequest\x1a..lemming.dataplane.sai.RemoveIpsecPortResponse\"\x00\x12\x84\x01\n" +
	"\x15SetIpsecPortAttribute\x123.lemming.dataplane.sai.SetIpsecPortAttributeRequest\x1a4.lemming.dataplane.sai.SetIpsecPortAttributeResponse\"\x00\x12\x84\x01\n" +
	"\x15GetIpsecPortAttribute\x123.lemming.dataplane.sai.GetIpsecPortAttributeRequest\x1a4.lemming.dataplane.sai.GetIpsecPortAttributeResponse\"\x00\x12x\n" +
	"\x11GetIpsecPortStats\x12/.lemming.dataplane.sai.GetIpsecPortStatsRequest\x1a0.lemming.dataplane.sai.GetIpsecPortStatsResponse\"\x00\x12l\n" +
	"\rCreateIpsecSa\x12+.lemming.dataplane.sai.CreateIpsecSaRequest\x1a,.lemming.dataplane.sai.CreateIpsecSaResponse\"\x00\x12l\n" +
	"\rRemoveIpsecSa\x12+.lemming.dataplane.sai.RemoveIpsecSaRequest\x1a,.lemming.dataplane.sai.RemoveIpsecSaResponse\"\x00\x12~\n" +
	"\x13SetIpsecSaAttribute\x121.lemming.dataplane.sai.SetIpsecSaAttributeRequest\x1a2.lemming.dataplane.sai.SetIpsecSaAttributeResponse\"\x00\x12~\n" +
	"\x13GetIpsecSaAttribute\x121.lemming.dataplane.sai.GetIpsecSaAttributeRequest\x1a2.lemming.dataplane.sai.GetIpsecSaAttributeResponse\"\x00\x12r\n" +
	"\x0fGetIpsecSaStats\x12-.lemming.dataplane.sai.GetIpsecSaStatsRequest\x1a..lemming.dataplane.sai.GetIpsecSaStatsResponse\"\x00B3Z1github.com/openconfig/lemming/dataplane/proto/saib\x06proto3"

var (
	file_dataplane_proto_sai_ipsec_proto_rawDescOnce sync.Once
	file_dataplane_proto_sai_ipsec_proto_rawDescData []byte
)

func file_dataplane_proto_sai_ipsec_proto_rawDescGZIP() []byte {
	file_dataplane_proto_sai_ipsec_proto_rawDescOnce.Do(func() {
		file_dataplane_proto_sai_ipsec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataplane_proto_sai_ipsec_proto_rawDesc), len(file_dataplane_proto_sai_ipsec_proto_rawDesc)))
	})
	return file_dataplane_proto_sai_ipsec_proto_rawDescData
}

var file_dataplane_proto_sai_ipsec_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dataplane_proto_sai_ipsec_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_dataplane_proto_sai_ipsec_proto_goTypes = []any{
	(IpsecAttr)(0),                        // 0: lemming.dataplane.sai.IpsecAttr
	(IpsecPortAttr)(0),                    // 1: lemming.dataplane.sai.IpsecPortAttr
	(IpsecSaAttr)(0),                      // 2: lemming.dataplane.sai.IpsecSaAttr
	(*CreateIpsecRequest)(nil),            // 3: lemming.dataplane.sai.CreateIpsecRequest
	(*CreateIpsecResponse)(nil),           // 4: lemming.dataplane.sai.CreateIpsecResponse
	(*RemoveIpsecRequest)(nil),            // 5: lemming.dataplane.sai.RemoveIpsecRequest
	(*RemoveIpsecResponse)(nil),           // 6: lemming.dataplane.sai.RemoveIpsecResponse
	(*SetIpsecAttributeRequest)(nil),      // 7: lemming.dataplane.sai.SetIpsecAttributeRequest
	(*SetIpsecAttributeResponse)(nil),     // 8: lemming.dataplane.sai.SetIpsecAttributeResponse
	(*GetIpsecAttributeRequest)(nil),      // 9: lemming.dataplane.sai.GetIpsecAttributeRequest
	(*GetIpsecAttributeResponse)(nil),     // 10: lemming.dataplane.sai.GetIpsecAttributeResponse
	(*CreateIpsecPortRequest)(nil),        // 11: lemming.dataplane.sai.CreateIpsecPortRequest
	(*CreateIpsecPortResponse)(nil),       // 12: lemming.dataplane.sai.CreateIpsecPortResponse
	(*RemoveIpsecPortRequest)(nil),        // 13: lemming.dataplane.sai.RemoveIpsecPortRequest
	(*RemoveIpsecPortResponse)(nil),       // 14: lemming.dataplane.sai.RemoveIpsecPortResponse
	(*SetIpsecPortAttributeRequest)(nil),  // 15: lemming.dataplane.sai.SetIpsecPortAttributeRequest
	(*SetIpsecPortAttributeResponse)(nil), // 16: lemming.dataplane.sai.SetIpsecPortAttributeResponse
	(*GetIpsecPortAttributeRequest)(nil),  // 17: lemming.dataplane.sai.GetIpsecPortAttributeRequest
	(*GetIpsecPortAttributeResponse)(nil), // 18: lemming.dataplane.sai.GetIpsecPortAttributeResponse
	(*GetIpsecPortStatsRequest)(nil),      // 19: lemming.dataplane.sai.GetIpsecPortStatsRequest
	(*GetIpsecPortStatsResponse)(nil),     // 20: lemming.dataplane.sai.GetIpsecPortStatsResponse
	(*CreateIpsecSaRequest)(nil),          // 21: lemming.dataplane.sai.CreateIpsecSaRequest
	(*CreateIpsecSaResponse)(nil),         // 22: lemming.dataplane.sai.CreateIpsecSaResponse
	(*RemoveIpsecSaRequest)(nil),          // 23: lemming.dataplane.sai.RemoveIpsecSaRequest
	(*RemoveIpsecSaResponse)(nil),         // 24: lemming.dataplane.sai.RemoveIpsecSaResponse
	(*SetIpsecSaAttributeRequest)(nil),    // 25: lemming.dataplane.sai.SetIpsecSaAttributeRequest
	(*SetIpsecSaAttributeResponse)(nil),   // 26: lemming.dataplane.sai.SetIpsecSaAttributeResponse
	(*GetIpsecSaAttributeRequest)(nil),    // 27: lemming.dataplane.sai.GetIpsecSaAttributeRequest
	(*GetIpsecSaAttributeResponse)(nil),   // 28: lemming.dataplane.sai.GetIpsecSaAttributeResponse
	(*GetIpsecSaStatsRequest)(nil),        // 29: lemming.dataplane.sai.GetIpsecSaStatsRequest
	(*GetIpsecSaStatsResponse)(nil),       // 30: lemming.dataplane.sai.GetIpsecSaStatsResponse
	(StatsMode)(0),                        // 31: lemming.dataplane.sai.StatsMode
	(*IpsecAttribute)(nil),                // 32: lemming.dataplane.sai.IpsecAttribute
	(SwitchSwitchingMode)(0),              // 33: lemming.dataplane.sai.SwitchSwitchingMode
	(StatsCountMode)(0),                   // 34: lemming.dataplane.sai.StatsCountMode
	(*IpsecPortAttribute)(nil),            // 35: lemming.dataplane.sai.IpsecPortAttribute
	(IpsecPortStat)(0),                    // 36: lemming.dataplane.sai.IpsecPortStat
	(IpsecDirection)(0),                   // 37: lemming.dataplane.sai.IpsecDirection
	(IpsecCipher)(0),                      // 38: lemming.dataplane.sai.IpsecCipher
	(*IpsecSaAttribute)(nil),              // 39: lemming.dataplane.sai.IpsecSaAttribute
	(IpsecSaStat)(0),                      // 40: lemming.dataplane.sai.IpsecSaStat
}
var file_dataplane_proto_sai_ipsec_proto_depIdxs = []int32{
	31, // 0: lemming.dataplane.sai.CreateIpsecRequest.stats_mode:type_name -> lemming.dataplane.sai.StatsMode
	31, // 1: lemming.dataplane.sai.SetIpsecAttributeRequest.stats_mode:type_name -> lemming.dataplane.sai.StatsMode
	0,  // 2: lemming.dataplane.sai.GetIpsecAttributeRequest.attr_type:type_name -> lemming.dataplane.sai.IpsecAttr
	32, // 3: lemming.dataplane.sai.GetIpsecAttributeResponse.attr:type_name -> lemming.dataplane.sai.IpsecAttribute
	33, // 4: lemming.dataplane.sai.CreateIpsecPortRequest.switch_switching_mode:type_name -> lemming.dataplane.sai.SwitchSwitchingMode
	34, // 5: lemming.dataplane.sai.CreateIpsecPortRequest.stats_count_mode:type_name -> lemming.dataplane.sai.StatsCountMode
	33, // 6: lemming.dataplane.sai.SetIpsecPortAttributeRequest.switch_switching_mode:type_name -> lemming.dataplane.sai.SwitchSwitchingMode
	34, // 7: lemming.dataplane.sai.SetIpsecPortAttributeRequest.stats_count_mode:type_name -> lemming.dataplane.sai.StatsCountMode
	1,  // 8: lemming.dataplane.sai.GetIpsecPortAttributeRequest.attr_type:type_name -> lemming.dataplane.sai.IpsecPortAttr
	35, // 9: lemming.dataplane.sai.GetIpsecPortAttributeResponse.attr:type_name -> lemming.dataplane.sai.IpsecPortAttribute
	36, // 10: lemming.dataplane.sai.GetIpsecPortStatsRequest.counter_ids:type_name -> lemming.dataplane.sai.IpsecPortStat
	37, // 11: lemming.dataplane.sai.CreateIpsecSaRequest.ipsec_direction:type_name -> lemming.dataplane.sai.IpsecDirection
	38, // 12: lemming.dataplane.sai.CreateIpsecSaRequest.ipsec_cipher:type_name -> lemming.dataplane.sai.IpsecCipher
	34, // 13: lemming.dataplane.sai.CreateIpsecSaRequest.stats_count_mode:type_name -> lemming.dataplane.sai.StatsCountMode
	34, // 14: lemming.dataplane.sai.SetIpsecSaAttributeRequest.stats_count_mode:type_name -> lemming.dataplane.sai.StatsCountMode
	2,  // 15: lemming.dataplane.sai.GetIpsecSaAttributeRequest.attr_type:type_name -> lemming.dataplane.sai.IpsecSaAttr
	39, // 16: lemming.dataplane.sai.GetIpsecSaAttributeResponse.attr:type_name -> lemming.dataplane.sai.IpsecSaAttribute
	40, // 17: lemming.dataplane.sai.GetIpsecSaStatsRequest.counter_ids:type_name -> lemming.dataplane.sai.IpsecSaStat
	3,  // 18: lemming.dataplane.sai.Ipsec.CreateIpsec:input_type -> lemming.dataplane.sai.CreateIpsecRequest
	5,  // 19: lemming.dataplane.sai.Ipsec.RemoveIpsec:input_type -> lemming.dataplane.sai.RemoveIpsecRequest
	7,  // 20: lemming.dataplane.sai.Ipsec.SetIpsecAttribute:input_type -> lemming.dataplane.sai.SetIpsecAttributeRequest
	9,  // 21: lemming.dataplane.sai.Ipsec.GetIpsecAttribute:input_type -> lemming.dataplane.sai.GetIpsecAttributeRequest
	11, // 22: lemming.dataplane.sai.Ipsec.CreateIpsecPort:input_type -> lemming.dataplane.sai.CreateIpsecPortRequest
	13, // 23: lemming.dataplane.sai.Ipsec.RemoveIpsecPort:input_type -> lemming.dataplane.sai.RemoveIpsecPortRequest
	15, // 24: lemming.dataplane.sai.Ipsec.SetIpsecPortAttribute:input_type -> lemming.dataplane.sai.SetIpsecPortAttributeRequest
	17, // 25: lemming.dataplane.sai.Ipsec.GetIpsecPortAttribute:input_type -> lemming.dataplane.sai.GetIpsecPortAttributeRequest
	19, // 26: lemming.dataplane.sai.Ipsec.GetIpsecPortStats:input_type -> lemming.dataplane.sai.GetIpsecPortStatsRequest
	21, // 27: lemming.dataplane.sai.Ipsec.CreateIpsecSa:input_type -> lemming.dataplane.sai.CreateIpsecSaRequest
	23, // 28: lemming.dataplane.sai.Ipsec.RemoveIpsecSa:input_type -> lemming.dataplane.sai.RemoveIpsecSaRequest
	25, // 29: lemming.dataplane.sai.Ipsec.SetIpsecSaAttribute:input_type -> lemming.dataplane.sai.SetIpsecSaAttributeRequest
	27, // 30: lemming.dataplane.sai.Ipsec.GetIpsecSaAttribute:input_type -> lemming.dataplane.sai.GetIpsecSaAttributeRequest
	29, // 31: lemming.dataplane.sai.Ipsec.GetIpsecSaStats:input_type -> lemming.dataplane.sai.GetIpsecSaStatsRequest
	4,  // 32: lemming.dataplane.sai.Ipsec.CreateIpsec:output_type -> lemming.dataplane.sai.CreateIpsecResponse
	6,  // 33: lemming.dataplane.sai.Ipsec.RemoveIpsec:output_type -> lemming.dataplane.sai.RemoveIpsecResponse
	8,  // 34: lemming.dataplane.sai.Ipsec.SetIpsecAttribute:output_type -> lemming.dataplane.sai.SetIpsecAttributeResponse
	10, // 35: lemming.dataplane.sai.Ipsec.GetIpsecAttribute:output_type -> lemming.dataplane.sai.GetIpsecAttributeResponse
	12, // 36: lemming.dataplane.sai.Ipsec.CreateIpsecPort:output_type -> lemming.dataplane.sai.CreateIpsecPortResponse
	14, // 37: lemming.dataplane.sai.Ipsec.RemoveIpsecPort:output_type -> lemming.dataplane.sai.RemoveIpsecPortResponse
	16, // 38: lemming.dataplane.sai.Ipsec.SetIpsecPortAttribute:output_type -> lemming.dataplane.sai.SetIpsecPortAttributeResponse
	18, // 39: lemming.dataplane.sai.Ipsec.GetIpsecPortAttribute:output_type -> lemming.dataplane.sai.GetIpsecPortAttributeResponse
	20, // 40: lemming.dataplane.sai.Ipsec.GetIpsecPortStats:output_type -> lemming.dataplane.sai.GetIpsecPortStatsResponse
	22, // 41: lemming.dataplane.sai.Ipsec.CreateIpsecSa:output_type -> lemming.dataplane.sai.CreateIpsecSaResponse
	24, // 42: lemming.dataplane.sai.Ipsec.RemoveIpsecSa:output_type -> lemming.dataplane.sai.RemoveIpsecSaResponse
	26, // 43: lemming.dataplane.sai.Ipsec.SetIpsecSaAttribute:output_type -> lemming.dataplane.sai.SetIpsecSaAttributeResponse
	28, // 44: lemming.dataplane.sai.Ipsec.GetIpsecSaAttribute:output_type -> lemming.dataplane.sai.GetIpsecSaAttributeResponse
	30, // 45: lemming.dataplane.sai.Ipsec.GetIpsecSaStats:output_type -> lemming.dataplane.sai.GetIpsecSaStatsResponse
	32, // [32:46] is the sub-list for method output_type
	18, // [18:32] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_dataplane_proto_sai_ipsec_proto_init() }
func file_dataplane_proto_sai_ipsec_proto_init() {
	if File_dataplane_proto_sai_ipsec_proto != nil {
		return
	}
	file_dataplane_proto_sai_common_proto_init()
	file_dataplane_proto_sai_ipsec_proto_msgTypes[0].OneofWrappers = []any{}
	file_dataplane_proto_sai_ipsec_proto_msgTypes[4].OneofWrappers = []any{}
	file_dataplane_proto_sai_ipsec_proto_msgTypes[8].OneofWrappers = []any{}
	file_dataplane_proto_sai_ipsec_proto_msgTypes[12].OneofWrappers = []any{}
	file_dataplane_proto_sai_ipsec_proto_msgTypes[18].OneofWrappers = []any{}
	file_dataplane_proto_sai_ipsec_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataplane_proto_sai_ipsec_proto_rawDesc), len(file_dataplane_proto_sai_ipsec_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataplane_proto_sai_ipsec_proto_goTypes,
		DependencyIndexes: file_dataplane_proto_sai_ipsec_proto_depIdxs,
		EnumInfos:         file_dataplane_proto_sai_ipsec_proto_enumTypes,
		MessageInfos:      file_dataplane_proto_sai_ipsec_proto_msgTypes,
	}.Build()
	File_dataplane_proto_sai_ipsec_proto = out.File
	file_dataplane_proto_sai_ipsec_proto_goTypes = nil
	file_dataplane_proto_sai_ipsec_proto_depIdxs = nil
}
