// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: dataplane/proto/sai/scheduler.proto

package sai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchedulerAttr int32

const (
	SchedulerAttr_SCHEDULER_ATTR_UNSPECIFIED              SchedulerAttr = 0
	SchedulerAttr_SCHEDULER_ATTR_SCHEDULING_TYPE          SchedulerAttr = 1
	SchedulerAttr_SCHEDULER_ATTR_SCHEDULING_WEIGHT        SchedulerAttr = 2
	SchedulerAttr_SCHEDULER_ATTR_METER_TYPE               SchedulerAttr = 3
	SchedulerAttr_SCHEDULER_ATTR_MIN_BANDWIDTH_RATE       SchedulerAttr = 4
	SchedulerAttr_SCHEDULER_ATTR_MIN_BANDWIDTH_BURST_RATE SchedulerAttr = 5
	SchedulerAttr_SCHEDULER_ATTR_MAX_BANDWIDTH_RATE       SchedulerAttr = 6
	SchedulerAttr_SCHEDULER_ATTR_MAX_BANDWIDTH_BURST_RATE SchedulerAttr = 7
)

// Enum value maps for SchedulerAttr.
var (
	SchedulerAttr_name = map[int32]string{
		0: "SCHEDULER_ATTR_UNSPECIFIED",
		1: "SCHEDULER_ATTR_SCHEDULING_TYPE",
		2: "SCHEDULER_ATTR_SCHEDULING_WEIGHT",
		3: "SCHEDULER_ATTR_METER_TYPE",
		4: "SCHEDULER_ATTR_MIN_BANDWIDTH_RATE",
		5: "SCHEDULER_ATTR_MIN_BANDWIDTH_BURST_RATE",
		6: "SCHEDULER_ATTR_MAX_BANDWIDTH_RATE",
		7: "SCHEDULER_ATTR_MAX_BANDWIDTH_BURST_RATE",
	}
	SchedulerAttr_value = map[string]int32{
		"SCHEDULER_ATTR_UNSPECIFIED":              0,
		"SCHEDULER_ATTR_SCHEDULING_TYPE":          1,
		"SCHEDULER_ATTR_SCHEDULING_WEIGHT":        2,
		"SCHEDULER_ATTR_METER_TYPE":               3,
		"SCHEDULER_ATTR_MIN_BANDWIDTH_RATE":       4,
		"SCHEDULER_ATTR_MIN_BANDWIDTH_BURST_RATE": 5,
		"SCHEDULER_ATTR_MAX_BANDWIDTH_RATE":       6,
		"SCHEDULER_ATTR_MAX_BANDWIDTH_BURST_RATE": 7,
	}
)

func (x SchedulerAttr) Enum() *SchedulerAttr {
	p := new(SchedulerAttr)
	*p = x
	return p
}

func (x SchedulerAttr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedulerAttr) Descriptor() protoreflect.EnumDescriptor {
	return file_dataplane_proto_sai_scheduler_proto_enumTypes[0].Descriptor()
}

func (SchedulerAttr) Type() protoreflect.EnumType {
	return &file_dataplane_proto_sai_scheduler_proto_enumTypes[0]
}

func (x SchedulerAttr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedulerAttr.Descriptor instead.
func (SchedulerAttr) EnumDescriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_scheduler_proto_rawDescGZIP(), []int{0}
}

type CreateSchedulerRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Switch                uint64                 `protobuf:"varint,1,opt,name=switch,proto3" json:"switch,omitempty"`
	SchedulingType        *SchedulingType        `protobuf:"varint,2,opt,name=scheduling_type,json=schedulingType,proto3,enum=lemming.dataplane.sai.SchedulingType,oneof" json:"scheduling_type,omitempty"`
	SchedulingWeight      *uint32                `protobuf:"varint,3,opt,name=scheduling_weight,json=schedulingWeight,proto3,oneof" json:"scheduling_weight,omitempty"`
	MeterType             *MeterType             `protobuf:"varint,4,opt,name=meter_type,json=meterType,proto3,enum=lemming.dataplane.sai.MeterType,oneof" json:"meter_type,omitempty"`
	MinBandwidthRate      *uint64                `protobuf:"varint,5,opt,name=min_bandwidth_rate,json=minBandwidthRate,proto3,oneof" json:"min_bandwidth_rate,omitempty"`
	MinBandwidthBurstRate *uint64                `protobuf:"varint,6,opt,name=min_bandwidth_burst_rate,json=minBandwidthBurstRate,proto3,oneof" json:"min_bandwidth_burst_rate,omitempty"`
	MaxBandwidthRate      *uint64                `protobuf:"varint,7,opt,name=max_bandwidth_rate,json=maxBandwidthRate,proto3,oneof" json:"max_bandwidth_rate,omitempty"`
	MaxBandwidthBurstRate *uint64                `protobuf:"varint,8,opt,name=max_bandwidth_burst_rate,json=maxBandwidthBurstRate,proto3,oneof" json:"max_bandwidth_burst_rate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateSchedulerRequest) Reset() {
	*x = CreateSchedulerRequest{}
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchedulerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchedulerRequest) ProtoMessage() {}

func (x *CreateSchedulerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchedulerRequest.ProtoReflect.Descriptor instead.
func (*CreateSchedulerRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSchedulerRequest) GetSwitch() uint64 {
	if x != nil {
		return x.Switch
	}
	return 0
}

func (x *CreateSchedulerRequest) GetSchedulingType() SchedulingType {
	if x != nil && x.SchedulingType != nil {
		return *x.SchedulingType
	}
	return SchedulingType_SCHEDULING_TYPE_UNSPECIFIED
}

func (x *CreateSchedulerRequest) GetSchedulingWeight() uint32 {
	if x != nil && x.SchedulingWeight != nil {
		return *x.SchedulingWeight
	}
	return 0
}

func (x *CreateSchedulerRequest) GetMeterType() MeterType {
	if x != nil && x.MeterType != nil {
		return *x.MeterType
	}
	return MeterType_METER_TYPE_UNSPECIFIED
}

func (x *CreateSchedulerRequest) GetMinBandwidthRate() uint64 {
	if x != nil && x.MinBandwidthRate != nil {
		return *x.MinBandwidthRate
	}
	return 0
}

func (x *CreateSchedulerRequest) GetMinBandwidthBurstRate() uint64 {
	if x != nil && x.MinBandwidthBurstRate != nil {
		return *x.MinBandwidthBurstRate
	}
	return 0
}

func (x *CreateSchedulerRequest) GetMaxBandwidthRate() uint64 {
	if x != nil && x.MaxBandwidthRate != nil {
		return *x.MaxBandwidthRate
	}
	return 0
}

func (x *CreateSchedulerRequest) GetMaxBandwidthBurstRate() uint64 {
	if x != nil && x.MaxBandwidthBurstRate != nil {
		return *x.MaxBandwidthBurstRate
	}
	return 0
}

type CreateSchedulerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchedulerResponse) Reset() {
	*x = CreateSchedulerResponse{}
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchedulerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchedulerResponse) ProtoMessage() {}

func (x *CreateSchedulerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchedulerResponse.ProtoReflect.Descriptor instead.
func (*CreateSchedulerResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSchedulerResponse) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveSchedulerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSchedulerRequest) Reset() {
	*x = RemoveSchedulerRequest{}
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSchedulerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSchedulerRequest) ProtoMessage() {}

func (x *RemoveSchedulerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSchedulerRequest.ProtoReflect.Descriptor instead.
func (*RemoveSchedulerRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveSchedulerRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveSchedulerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSchedulerResponse) Reset() {
	*x = RemoveSchedulerResponse{}
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSchedulerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSchedulerResponse) ProtoMessage() {}

func (x *RemoveSchedulerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSchedulerResponse.ProtoReflect.Descriptor instead.
func (*RemoveSchedulerResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_scheduler_proto_rawDescGZIP(), []int{3}
}

type SetSchedulerAttributeRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Oid                   uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	SchedulingType        *SchedulingType        `protobuf:"varint,2,opt,name=scheduling_type,json=schedulingType,proto3,enum=lemming.dataplane.sai.SchedulingType,oneof" json:"scheduling_type,omitempty"`
	SchedulingWeight      *uint32                `protobuf:"varint,3,opt,name=scheduling_weight,json=schedulingWeight,proto3,oneof" json:"scheduling_weight,omitempty"`
	MeterType             *MeterType             `protobuf:"varint,4,opt,name=meter_type,json=meterType,proto3,enum=lemming.dataplane.sai.MeterType,oneof" json:"meter_type,omitempty"`
	MinBandwidthRate      *uint64                `protobuf:"varint,5,opt,name=min_bandwidth_rate,json=minBandwidthRate,proto3,oneof" json:"min_bandwidth_rate,omitempty"`
	MinBandwidthBurstRate *uint64                `protobuf:"varint,6,opt,name=min_bandwidth_burst_rate,json=minBandwidthBurstRate,proto3,oneof" json:"min_bandwidth_burst_rate,omitempty"`
	MaxBandwidthRate      *uint64                `protobuf:"varint,7,opt,name=max_bandwidth_rate,json=maxBandwidthRate,proto3,oneof" json:"max_bandwidth_rate,omitempty"`
	MaxBandwidthBurstRate *uint64                `protobuf:"varint,8,opt,name=max_bandwidth_burst_rate,json=maxBandwidthBurstRate,proto3,oneof" json:"max_bandwidth_burst_rate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SetSchedulerAttributeRequest) Reset() {
	*x = SetSchedulerAttributeRequest{}
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSchedulerAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSchedulerAttributeRequest) ProtoMessage() {}

func (x *SetSchedulerAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSchedulerAttributeRequest.ProtoReflect.Descriptor instead.
func (*SetSchedulerAttributeRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *SetSchedulerAttributeRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *SetSchedulerAttributeRequest) GetSchedulingType() SchedulingType {
	if x != nil && x.SchedulingType != nil {
		return *x.SchedulingType
	}
	return SchedulingType_SCHEDULING_TYPE_UNSPECIFIED
}

func (x *SetSchedulerAttributeRequest) GetSchedulingWeight() uint32 {
	if x != nil && x.SchedulingWeight != nil {
		return *x.SchedulingWeight
	}
	return 0
}

func (x *SetSchedulerAttributeRequest) GetMeterType() MeterType {
	if x != nil && x.MeterType != nil {
		return *x.MeterType
	}
	return MeterType_METER_TYPE_UNSPECIFIED
}

func (x *SetSchedulerAttributeRequest) GetMinBandwidthRate() uint64 {
	if x != nil && x.MinBandwidthRate != nil {
		return *x.MinBandwidthRate
	}
	return 0
}

func (x *SetSchedulerAttributeRequest) GetMinBandwidthBurstRate() uint64 {
	if x != nil && x.MinBandwidthBurstRate != nil {
		return *x.MinBandwidthBurstRate
	}
	return 0
}

func (x *SetSchedulerAttributeRequest) GetMaxBandwidthRate() uint64 {
	if x != nil && x.MaxBandwidthRate != nil {
		return *x.MaxBandwidthRate
	}
	return 0
}

func (x *SetSchedulerAttributeRequest) GetMaxBandwidthBurstRate() uint64 {
	if x != nil && x.MaxBandwidthBurstRate != nil {
		return *x.MaxBandwidthBurstRate
	}
	return 0
}

type SetSchedulerAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSchedulerAttributeResponse) Reset() {
	*x = SetSchedulerAttributeResponse{}
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSchedulerAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSchedulerAttributeResponse) ProtoMessage() {}

func (x *SetSchedulerAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSchedulerAttributeResponse.ProtoReflect.Descriptor instead.
func (*SetSchedulerAttributeResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_scheduler_proto_rawDescGZIP(), []int{5}
}

type GetSchedulerAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           uint64                 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	AttrType      []SchedulerAttr        `protobuf:"varint,2,rep,packed,name=attr_type,json=attrType,proto3,enum=lemming.dataplane.sai.SchedulerAttr" json:"attr_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulerAttributeRequest) Reset() {
	*x = GetSchedulerAttributeRequest{}
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerAttributeRequest) ProtoMessage() {}

func (x *GetSchedulerAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetSchedulerAttributeRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *GetSchedulerAttributeRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *GetSchedulerAttributeRequest) GetAttrType() []SchedulerAttr {
	if x != nil {
		return x.AttrType
	}
	return nil
}

type GetSchedulerAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *SchedulerAttribute    `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulerAttributeResponse) Reset() {
	*x = GetSchedulerAttributeResponse{}
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerAttributeResponse) ProtoMessage() {}

func (x *GetSchedulerAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_sai_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerAttributeResponse.ProtoReflect.Descriptor instead.
func (*GetSchedulerAttributeResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_sai_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *GetSchedulerAttributeResponse) GetAttr() *SchedulerAttribute {
	if x != nil {
		return x.Attr
	}
	return nil
}

var File_dataplane_proto_sai_scheduler_proto protoreflect.FileDescriptor

const file_dataplane_proto_sai_scheduler_proto_rawDesc = "" +
	"\n" +
	"#dataplane/proto/sai/scheduler.proto\x12\x15lemming.dataplane.sai\x1a dataplane/proto/sai/common.proto\"\xc0\x05\n" +
	"\x16CreateSchedulerRequest\x12\x16\n" +
	"\x06switch\x18\x01 \x01(\x04R\x06switch\x12[\n" +
	"\x0fscheduling_type\x18\x02 \x01(\x0e2%.lemming.dataplane.sai.SchedulingTypeB\x06\xf0ܓ\xad\x0f\x01H\x00R\x0eschedulingType\x88\x01\x01\x128\n" +
	"\x11scheduling_weight\x18\x03 \x01(\rB\x06\xf0ܓ\xad\x0f\x02H\x01R\x10schedulingWeight\x88\x01\x01\x12L\n" +
	"\n" +
	"meter_type\x18\x04 \x01(\x0e2 .lemming.dataplane.sai.MeterTypeB\x06\xf0ܓ\xad\x0f\x03H\x02R\tmeterType\x88\x01\x01\x129\n" +
	"\x12min_bandwidth_rate\x18\x05 \x01(\x04B\x06\xf0ܓ\xad\x0f\x04H\x03R\x10minBandwidthRate\x88\x01\x01\x12D\n" +
	"\x18min_bandwidth_burst_rate\x18\x06 \x01(\x04B\x06\xf0ܓ\xad\x0f\x05H\x04R\x15minBandwidthBurstRate\x88\x01\x01\x129\n" +
	"\x12max_bandwidth_rate\x18\a \x01(\x04B\x06\xf0ܓ\xad\x0f\x06H\x05R\x10maxBandwidthRate\x88\x01\x01\x12D\n" +
	"\x18max_bandwidth_burst_rate\x18\b \x01(\x04B\x06\xf0ܓ\xad\x0f\aH\x06R\x15maxBandwidthBurstRate\x88\x01\x01:\x06\xa0\xa9\x90\xad\x0f\x17B\x12\n" +
	"\x10_scheduling_typeB\x14\n" +
	"\x12_scheduling_weightB\r\n" +
	"\v_meter_typeB\x15\n" +
	"\x13_min_bandwidth_rateB\x1b\n" +
	"\x19_min_bandwidth_burst_rateB\x15\n" +
	"\x13_max_bandwidth_rateB\x1b\n" +
	"\x19_max_bandwidth_burst_rate\"+\n" +
	"\x17CreateSchedulerResponse\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\"*\n" +
	"\x16RemoveSchedulerRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\"\x19\n" +
	"\x17RemoveSchedulerResponse\"\xb8\x05\n" +
	"\x1cSetSchedulerAttributeRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\x12[\n" +
	"\x0fscheduling_type\x18\x02 \x01(\x0e2%.lemming.dataplane.sai.SchedulingTypeB\x06\xf0ܓ\xad\x0f\x01H\x00R\x0eschedulingType\x88\x01\x01\x128\n" +
	"\x11scheduling_weight\x18\x03 \x01(\rB\x06\xf0ܓ\xad\x0f\x02H\x01R\x10schedulingWeight\x88\x01\x01\x12L\n" +
	"\n" +
	"meter_type\x18\x04 \x01(\x0e2 .lemming.dataplane.sai.MeterTypeB\x06\xf0ܓ\xad\x0f\x03H\x02R\tmeterType\x88\x01\x01\x129\n" +
	"\x12min_bandwidth_rate\x18\x05 \x01(\x04B\x06\xf0ܓ\xad\x0f\x04H\x03R\x10minBandwidthRate\x88\x01\x01\x12D\n" +
	"\x18min_bandwidth_burst_rate\x18\x06 \x01(\x04B\x06\xf0ܓ\xad\x0f\x05H\x04R\x15minBandwidthBurstRate\x88\x01\x01\x129\n" +
	"\x12max_bandwidth_rate\x18\a \x01(\x04B\x06\xf0ܓ\xad\x0f\x06H\x05R\x10maxBandwidthRate\x88\x01\x01\x12D\n" +
	"\x18max_bandwidth_burst_rate\x18\b \x01(\x04B\x06\xf0ܓ\xad\x0f\aH\x06R\x15maxBandwidthBurstRate\x88\x01\x01B\x12\n" +
	"\x10_scheduling_typeB\x14\n" +
	"\x12_scheduling_weightB\r\n" +
	"\v_meter_typeB\x15\n" +
	"\x13_min_bandwidth_rateB\x1b\n" +
	"\x19_min_bandwidth_burst_rateB\x15\n" +
	"\x13_max_bandwidth_rateB\x1b\n" +
	"\x19_max_bandwidth_burst_rate\"\x1f\n" +
	"\x1dSetSchedulerAttributeResponse\"s\n" +
	"\x1cGetSchedulerAttributeRequest\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\x04R\x03oid\x12A\n" +
	"\tattr_type\x18\x02 \x03(\x0e2$.lemming.dataplane.sai.SchedulerAttrR\battrType\"^\n" +
	"\x1dGetSchedulerAttributeResponse\x12=\n" +
	"\x04attr\x18\x01 \x01(\v2).lemming.dataplane.sai.SchedulerAttributeR\x04attr*\xc0\x02\n" +
	"\rSchedulerAttr\x12\x1e\n" +
	"\x1aSCHEDULER_ATTR_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSCHEDULER_ATTR_SCHEDULING_TYPE\x10\x01\x12$\n" +
	" SCHEDULER_ATTR_SCHEDULING_WEIGHT\x10\x02\x12\x1d\n" +
	"\x19SCHEDULER_ATTR_METER_TYPE\x10\x03\x12%\n" +
	"!SCHEDULER_ATTR_MIN_BANDWIDTH_RATE\x10\x04\x12+\n" +
	"'SCHEDULER_ATTR_MIN_BANDWIDTH_BURST_RATE\x10\x05\x12%\n" +
	"!SCHEDULER_ATTR_MAX_BANDWIDTH_RATE\x10\x06\x12+\n" +
	"'SCHEDULER_ATTR_MAX_BANDWIDTH_BURST_RATE\x10\a2\x81\x04\n" +
	"\tScheduler\x12r\n" +
	"\x0fCreateScheduler\x12-.lemming.dataplane.sai.CreateSchedulerRequest\x1a..lemming.dataplane.sai.CreateSchedulerResponse\"\x00\x12r\n" +
	"\x0fRemoveScheduler\x12-.lemming.dataplane.sai.RemoveSchedulerRequest\x1a..lemming.dataplane.sai.RemoveSchedulerResponse\"\x00\x12\x84\x01\n" +
	"\x15SetSchedulerAttribute\x123.lemming.dataplane.sai.SetSchedulerAttributeRequest\x1a4.lemming.dataplane.sai.SetSchedulerAttributeResponse\"\x00\x12\x84\x01\n" +
	"\x15GetSchedulerAttribute\x123.lemming.dataplane.sai.GetSchedulerAttributeRequest\x1a4.lemming.dataplane.sai.GetSchedulerAttributeResponse\"\x00B3Z1github.com/openconfig/lemming/dataplane/proto/saib\x06proto3"

var (
	file_dataplane_proto_sai_scheduler_proto_rawDescOnce sync.Once
	file_dataplane_proto_sai_scheduler_proto_rawDescData []byte
)

func file_dataplane_proto_sai_scheduler_proto_rawDescGZIP() []byte {
	file_dataplane_proto_sai_scheduler_proto_rawDescOnce.Do(func() {
		file_dataplane_proto_sai_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataplane_proto_sai_scheduler_proto_rawDesc), len(file_dataplane_proto_sai_scheduler_proto_rawDesc)))
	})
	return file_dataplane_proto_sai_scheduler_proto_rawDescData
}

var file_dataplane_proto_sai_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dataplane_proto_sai_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_dataplane_proto_sai_scheduler_proto_goTypes = []any{
	(SchedulerAttr)(0),                    // 0: lemming.dataplane.sai.SchedulerAttr
	(*CreateSchedulerRequest)(nil),        // 1: lemming.dataplane.sai.CreateSchedulerRequest
	(*CreateSchedulerResponse)(nil),       // 2: lemming.dataplane.sai.CreateSchedulerResponse
	(*RemoveSchedulerRequest)(nil),        // 3: lemming.dataplane.sai.RemoveSchedulerRequest
	(*RemoveSchedulerResponse)(nil),       // 4: lemming.dataplane.sai.RemoveSchedulerResponse
	(*SetSchedulerAttributeRequest)(nil),  // 5: lemming.dataplane.sai.SetSchedulerAttributeRequest
	(*SetSchedulerAttributeResponse)(nil), // 6: lemming.dataplane.sai.SetSchedulerAttributeResponse
	(*GetSchedulerAttributeRequest)(nil),  // 7: lemming.dataplane.sai.GetSchedulerAttributeRequest
	(*GetSchedulerAttributeResponse)(nil), // 8: lemming.dataplane.sai.GetSchedulerAttributeResponse
	(SchedulingType)(0),                   // 9: lemming.dataplane.sai.SchedulingType
	(MeterType)(0),                        // 10: lemming.dataplane.sai.MeterType
	(*SchedulerAttribute)(nil),            // 11: lemming.dataplane.sai.SchedulerAttribute
}
var file_dataplane_proto_sai_scheduler_proto_depIdxs = []int32{
	9,  // 0: lemming.dataplane.sai.CreateSchedulerRequest.scheduling_type:type_name -> lemming.dataplane.sai.SchedulingType
	10, // 1: lemming.dataplane.sai.CreateSchedulerRequest.meter_type:type_name -> lemming.dataplane.sai.MeterType
	9,  // 2: lemming.dataplane.sai.SetSchedulerAttributeRequest.scheduling_type:type_name -> lemming.dataplane.sai.SchedulingType
	10, // 3: lemming.dataplane.sai.SetSchedulerAttributeRequest.meter_type:type_name -> lemming.dataplane.sai.MeterType
	0,  // 4: lemming.dataplane.sai.GetSchedulerAttributeRequest.attr_type:type_name -> lemming.dataplane.sai.SchedulerAttr
	11, // 5: lemming.dataplane.sai.GetSchedulerAttributeResponse.attr:type_name -> lemming.dataplane.sai.SchedulerAttribute
	1,  // 6: lemming.dataplane.sai.Scheduler.CreateScheduler:input_type -> lemming.dataplane.sai.CreateSchedulerRequest
	3,  // 7: lemming.dataplane.sai.Scheduler.RemoveScheduler:input_type -> lemming.dataplane.sai.RemoveSchedulerRequest
	5,  // 8: lemming.dataplane.sai.Scheduler.SetSchedulerAttribute:input_type -> lemming.dataplane.sai.SetSchedulerAttributeRequest
	7,  // 9: lemming.dataplane.sai.Scheduler.GetSchedulerAttribute:input_type -> lemming.dataplane.sai.GetSchedulerAttributeRequest
	2,  // 10: lemming.dataplane.sai.Scheduler.CreateScheduler:output_type -> lemming.dataplane.sai.CreateSchedulerResponse
	4,  // 11: lemming.dataplane.sai.Scheduler.RemoveScheduler:output_type -> lemming.dataplane.sai.RemoveSchedulerResponse
	6,  // 12: lemming.dataplane.sai.Scheduler.SetSchedulerAttribute:output_type -> lemming.dataplane.sai.SetSchedulerAttributeResponse
	8,  // 13: lemming.dataplane.sai.Scheduler.GetSchedulerAttribute:output_type -> lemming.dataplane.sai.GetSchedulerAttributeResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_dataplane_proto_sai_scheduler_proto_init() }
func file_dataplane_proto_sai_scheduler_proto_init() {
	if File_dataplane_proto_sai_scheduler_proto != nil {
		return
	}
	file_dataplane_proto_sai_common_proto_init()
	file_dataplane_proto_sai_scheduler_proto_msgTypes[0].OneofWrappers = []any{}
	file_dataplane_proto_sai_scheduler_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataplane_proto_sai_scheduler_proto_rawDesc), len(file_dataplane_proto_sai_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataplane_proto_sai_scheduler_proto_goTypes,
		DependencyIndexes: file_dataplane_proto_sai_scheduler_proto_depIdxs,
		EnumInfos:         file_dataplane_proto_sai_scheduler_proto_enumTypes,
		MessageInfos:      file_dataplane_proto_sai_scheduler_proto_msgTypes,
	}.Build()
	File_dataplane_proto_sai_scheduler_proto = out.File
	file_dataplane_proto_sai_scheduler_proto_goTypes = nil
	file_dataplane_proto_sai_scheduler_proto_depIdxs = nil
}
