load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "definedsets",
    srcs = [
        "definedsets-0.go",
        "definedsets-1.go",
        "definedsets-2.go",
        "definedsets-3.go",
        "definedsets-4.go",
        "definedsets-5.go",
        "definedsets-6.go",
        "definedsets-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/definedsets",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
