#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.10
if [ "$1" = "remove" ] && [ -x "/etc/init.d/lucius-pkthandler" ] ; then
	chmod -x "/etc/init.d/lucius-pkthandler" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d lucius-pkthandler remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.11.10
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.11.10
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'lucius-pkthandler.service' >/dev/null || true
	fi
fi
# End automatically added section
