#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.10
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/lucius-pkthandler" ] ; then
	chmod +x "/etc/init.d/lucius-pkthandler" >/dev/null || true
fi
# End automatically added section
