#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.10
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/lucius-pkthandler" ] ; then
	invoke-rc.d lucius-pkthandler stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.11.10
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'lucius-pkthandler.service' >/dev/null || true
fi
# End automatically added section
