load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "bgpgue",
    srcs = [
        "bgpgue-0.go",
        "bgpgue-1.go",
        "bgpgue-2.go",
        "bgpgue-3.go",
        "bgpgue-4.go",
        "bgpgue-5.go",
        "bgpgue-6.go",
        "bgpgue-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/bgpgue",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
