FROM docker.io/debian:bookworm
WORKDIR /build
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libprotobuf-dev \
    protobuf-compiler \
    libgrpc++-dev \
    protobuf-compiler-grpc \
    libgoogle-glog-dev \
    wget \
    patch \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY patches/sai.patch sai.patch
RUN wget -q https://github.com/opencomputeproject/SAI/archive/refs/tags/v1.15.0.tar.gz && tar xf v1.15.0.tar.gz && rm v1.15.0.tar.gz
RUN mkdir external && mv SAI-1.15.0 external/com_github_opencomputeproject_sai && patch -p1 -d external/com_github_opencomputeproject_sai < sai.patch
COPY dataplane/proto/sai/*.proto dataplane/proto/sai/
COPY dataplane/standalone/sai/*.cc dataplane/standalone/sai/
COPY dataplane/standalone/sai/*.h dataplane/standalone/sai/
COPY dataplane/standalone/entrypoint.cc dataplane/standalone/entrypoint.cc
COPY Makefile .
RUN make lucius-libsai -j 48
