apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: lemming-operator
build:
  artifacts:
  - image: controller
    docker:
      dockerfile: Dockerfile.operator
manifests:
  kustomize:
    paths:
    - operator/config/default
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: lemming
requires:
- configs:
  - lemming-operator
build:
  artifacts:
  - image: lemming
    docker:
      dockerfile: Dockerfile.lemming
  local:
    useBuildkit: true
manifests:
  rawYaml:
  - operator/config/samples/lemming_v1alpha1_lemming.yaml
deploy:
  kubectl: {}
resourceSelector:
  allow:
  - groupKind: Lemming.lemming.openconfig.net
    image:
    - .*
    labels:
    - .*