load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "attributes",
    srcs = ["attributes.go"],
    importpath = "github.com/openconfig/lemming/dataplane/forwarding/attributes",
    visibility = ["//visibility:public"],
)
