load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "docparser",
    srcs = ["docparser.go"],
    importpath = "github.com/openconfig/lemming/dataplane/apigen/docparser",
    visibility = ["//visibility:public"],
)
