load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "fwdattribute",
    srcs = ["attribute.go"],
    importpath = "github.com/openconfig/lemming/dataplane/forwarding/infra/fwdattribute",
    visibility = ["//visibility:public"],
)
