load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "keychain",
    srcs = [
        "keychain-0.go",
        "keychain-1.go",
        "keychain-2.go",
        "keychain-3.go",
        "keychain-4.go",
        "keychain-5.go",
        "keychain-6.go",
        "keychain-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/keychain",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
