load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "routingpolicy",
    srcs = [
        "routingpolicy-0.go",
        "routingpolicy-1.go",
        "routingpolicy-2.go",
        "routingpolicy-3.go",
        "routingpolicy-4.go",
        "routingpolicy-5.go",
        "routingpolicy-6.go",
        "routingpolicy-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/routingpolicy",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
