// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: dataplane/standalone/proto/isolation_group.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsolationGroupAttr int32

const (
	IsolationGroupAttr_ISOLATION_GROUP_ATTR_UNSPECIFIED           IsolationGroupAttr = 0
	IsolationGroupAttr_ISOLATION_GROUP_ATTR_TYPE                  IsolationGroupAttr = 1
	IsolationGroupAttr_ISOLATION_GROUP_ATTR_ISOLATION_MEMBER_LIST IsolationGroupAttr = 2
)

// Enum value maps for IsolationGroupAttr.
var (
	IsolationGroupAttr_name = map[int32]string{
		0: "ISOLATION_GROUP_ATTR_UNSPECIFIED",
		1: "ISOLATION_GROUP_ATTR_TYPE",
		2: "ISOLATION_GROUP_ATTR_ISOLATION_MEMBER_LIST",
	}
	IsolationGroupAttr_value = map[string]int32{
		"ISOLATION_GROUP_ATTR_UNSPECIFIED":           0,
		"ISOLATION_GROUP_ATTR_TYPE":                  1,
		"ISOLATION_GROUP_ATTR_ISOLATION_MEMBER_LIST": 2,
	}
)

func (x IsolationGroupAttr) Enum() *IsolationGroupAttr {
	p := new(IsolationGroupAttr)
	*p = x
	return p
}

func (x IsolationGroupAttr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IsolationGroupAttr) Descriptor() protoreflect.EnumDescriptor {
	return file_dataplane_standalone_proto_isolation_group_proto_enumTypes[0].Descriptor()
}

func (IsolationGroupAttr) Type() protoreflect.EnumType {
	return &file_dataplane_standalone_proto_isolation_group_proto_enumTypes[0]
}

func (x IsolationGroupAttr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IsolationGroupAttr.Descriptor instead.
func (IsolationGroupAttr) EnumDescriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{0}
}

type IsolationGroupMemberAttr int32

const (
	IsolationGroupMemberAttr_ISOLATION_GROUP_MEMBER_ATTR_UNSPECIFIED        IsolationGroupMemberAttr = 0
	IsolationGroupMemberAttr_ISOLATION_GROUP_MEMBER_ATTR_ISOLATION_GROUP_ID IsolationGroupMemberAttr = 1
	IsolationGroupMemberAttr_ISOLATION_GROUP_MEMBER_ATTR_ISOLATION_OBJECT   IsolationGroupMemberAttr = 2
)

// Enum value maps for IsolationGroupMemberAttr.
var (
	IsolationGroupMemberAttr_name = map[int32]string{
		0: "ISOLATION_GROUP_MEMBER_ATTR_UNSPECIFIED",
		1: "ISOLATION_GROUP_MEMBER_ATTR_ISOLATION_GROUP_ID",
		2: "ISOLATION_GROUP_MEMBER_ATTR_ISOLATION_OBJECT",
	}
	IsolationGroupMemberAttr_value = map[string]int32{
		"ISOLATION_GROUP_MEMBER_ATTR_UNSPECIFIED":        0,
		"ISOLATION_GROUP_MEMBER_ATTR_ISOLATION_GROUP_ID": 1,
		"ISOLATION_GROUP_MEMBER_ATTR_ISOLATION_OBJECT":   2,
	}
)

func (x IsolationGroupMemberAttr) Enum() *IsolationGroupMemberAttr {
	p := new(IsolationGroupMemberAttr)
	*p = x
	return p
}

func (x IsolationGroupMemberAttr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IsolationGroupMemberAttr) Descriptor() protoreflect.EnumDescriptor {
	return file_dataplane_standalone_proto_isolation_group_proto_enumTypes[1].Descriptor()
}

func (IsolationGroupMemberAttr) Type() protoreflect.EnumType {
	return &file_dataplane_standalone_proto_isolation_group_proto_enumTypes[1]
}

func (x IsolationGroupMemberAttr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IsolationGroupMemberAttr.Descriptor instead.
func (IsolationGroupMemberAttr) EnumDescriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{1}
}

type CreateIsolationGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Switch uint64              `protobuf:"varint,1,opt,name=switch,proto3" json:"switch,omitempty"`
	Type   *IsolationGroupType `protobuf:"varint,2,opt,name=type,proto3,enum=lemming.dataplane.sai.IsolationGroupType,oneof" json:"type,omitempty"`
}

func (x *CreateIsolationGroupRequest) Reset() {
	*x = CreateIsolationGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIsolationGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIsolationGroupRequest) ProtoMessage() {}

func (x *CreateIsolationGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIsolationGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateIsolationGroupRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIsolationGroupRequest) GetSwitch() uint64 {
	if x != nil {
		return x.Switch
	}
	return 0
}

func (x *CreateIsolationGroupRequest) GetType() IsolationGroupType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return IsolationGroupType_ISOLATION_GROUP_TYPE_UNSPECIFIED
}

type CreateIsolationGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid uint64 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
}

func (x *CreateIsolationGroupResponse) Reset() {
	*x = CreateIsolationGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIsolationGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIsolationGroupResponse) ProtoMessage() {}

func (x *CreateIsolationGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIsolationGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateIsolationGroupResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIsolationGroupResponse) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveIsolationGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid uint64 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
}

func (x *RemoveIsolationGroupRequest) Reset() {
	*x = RemoveIsolationGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveIsolationGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIsolationGroupRequest) ProtoMessage() {}

func (x *RemoveIsolationGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIsolationGroupRequest.ProtoReflect.Descriptor instead.
func (*RemoveIsolationGroupRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveIsolationGroupRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveIsolationGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveIsolationGroupResponse) Reset() {
	*x = RemoveIsolationGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveIsolationGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIsolationGroupResponse) ProtoMessage() {}

func (x *RemoveIsolationGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIsolationGroupResponse.ProtoReflect.Descriptor instead.
func (*RemoveIsolationGroupResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{3}
}

type GetIsolationGroupAttributeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid      uint64               `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	AttrType []IsolationGroupAttr `protobuf:"varint,2,rep,packed,name=attr_type,json=attrType,proto3,enum=lemming.dataplane.sai.IsolationGroupAttr" json:"attr_type,omitempty"`
}

func (x *GetIsolationGroupAttributeRequest) Reset() {
	*x = GetIsolationGroupAttributeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIsolationGroupAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsolationGroupAttributeRequest) ProtoMessage() {}

func (x *GetIsolationGroupAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsolationGroupAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetIsolationGroupAttributeRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{4}
}

func (x *GetIsolationGroupAttributeRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *GetIsolationGroupAttributeRequest) GetAttrType() []IsolationGroupAttr {
	if x != nil {
		return x.AttrType
	}
	return nil
}

type GetIsolationGroupAttributeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attr *IsolationGroupAttribute `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *GetIsolationGroupAttributeResponse) Reset() {
	*x = GetIsolationGroupAttributeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIsolationGroupAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsolationGroupAttributeResponse) ProtoMessage() {}

func (x *GetIsolationGroupAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsolationGroupAttributeResponse.ProtoReflect.Descriptor instead.
func (*GetIsolationGroupAttributeResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{5}
}

func (x *GetIsolationGroupAttributeResponse) GetAttr() *IsolationGroupAttribute {
	if x != nil {
		return x.Attr
	}
	return nil
}

type CreateIsolationGroupMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Switch           uint64  `protobuf:"varint,1,opt,name=switch,proto3" json:"switch,omitempty"`
	IsolationGroupId *uint64 `protobuf:"varint,2,opt,name=isolation_group_id,json=isolationGroupId,proto3,oneof" json:"isolation_group_id,omitempty"`
	IsolationObject  *uint64 `protobuf:"varint,3,opt,name=isolation_object,json=isolationObject,proto3,oneof" json:"isolation_object,omitempty"`
}

func (x *CreateIsolationGroupMemberRequest) Reset() {
	*x = CreateIsolationGroupMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIsolationGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIsolationGroupMemberRequest) ProtoMessage() {}

func (x *CreateIsolationGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIsolationGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*CreateIsolationGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{6}
}

func (x *CreateIsolationGroupMemberRequest) GetSwitch() uint64 {
	if x != nil {
		return x.Switch
	}
	return 0
}

func (x *CreateIsolationGroupMemberRequest) GetIsolationGroupId() uint64 {
	if x != nil && x.IsolationGroupId != nil {
		return *x.IsolationGroupId
	}
	return 0
}

func (x *CreateIsolationGroupMemberRequest) GetIsolationObject() uint64 {
	if x != nil && x.IsolationObject != nil {
		return *x.IsolationObject
	}
	return 0
}

type CreateIsolationGroupMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid uint64 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
}

func (x *CreateIsolationGroupMemberResponse) Reset() {
	*x = CreateIsolationGroupMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIsolationGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIsolationGroupMemberResponse) ProtoMessage() {}

func (x *CreateIsolationGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIsolationGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*CreateIsolationGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{7}
}

func (x *CreateIsolationGroupMemberResponse) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveIsolationGroupMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid uint64 `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
}

func (x *RemoveIsolationGroupMemberRequest) Reset() {
	*x = RemoveIsolationGroupMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveIsolationGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIsolationGroupMemberRequest) ProtoMessage() {}

func (x *RemoveIsolationGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIsolationGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveIsolationGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveIsolationGroupMemberRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type RemoveIsolationGroupMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveIsolationGroupMemberResponse) Reset() {
	*x = RemoveIsolationGroupMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveIsolationGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIsolationGroupMemberResponse) ProtoMessage() {}

func (x *RemoveIsolationGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIsolationGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveIsolationGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{9}
}

type GetIsolationGroupMemberAttributeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid      uint64                     `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	AttrType []IsolationGroupMemberAttr `protobuf:"varint,2,rep,packed,name=attr_type,json=attrType,proto3,enum=lemming.dataplane.sai.IsolationGroupMemberAttr" json:"attr_type,omitempty"`
}

func (x *GetIsolationGroupMemberAttributeRequest) Reset() {
	*x = GetIsolationGroupMemberAttributeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIsolationGroupMemberAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsolationGroupMemberAttributeRequest) ProtoMessage() {}

func (x *GetIsolationGroupMemberAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsolationGroupMemberAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetIsolationGroupMemberAttributeRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{10}
}

func (x *GetIsolationGroupMemberAttributeRequest) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *GetIsolationGroupMemberAttributeRequest) GetAttrType() []IsolationGroupMemberAttr {
	if x != nil {
		return x.AttrType
	}
	return nil
}

type GetIsolationGroupMemberAttributeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attr *IsolationGroupMemberAttribute `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *GetIsolationGroupMemberAttributeResponse) Reset() {
	*x = GetIsolationGroupMemberAttributeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIsolationGroupMemberAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsolationGroupMemberAttributeResponse) ProtoMessage() {}

func (x *GetIsolationGroupMemberAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_standalone_proto_isolation_group_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsolationGroupMemberAttributeResponse.ProtoReflect.Descriptor instead.
func (*GetIsolationGroupMemberAttributeResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP(), []int{11}
}

func (x *GetIsolationGroupMemberAttributeResponse) GetAttr() *IsolationGroupMemberAttribute {
	if x != nil {
		return x.Attr
	}
	return nil
}

var File_dataplane_standalone_proto_isolation_group_proto protoreflect.FileDescriptor

var file_dataplane_standalone_proto_isolation_group_proto_rawDesc = []byte{
	0x0a, 0x30, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x6e,
	0x64, 0x61, 0x6c, 0x6f, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x73, 0x6f,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x1a, 0x27, 0x64, 0x61, 0x74, 0x61, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x6c, 0x6f, 0x6e, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x73, 0x6f,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x48, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69,
	0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69,
	0x2e, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54,
	0x79, 0x70, 0x65, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x01, 0x48, 0x00, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x30, 0x0a,
	0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x22,
	0x2f, 0x0a, 0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6f, 0x69, 0x64,
	0x22, 0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x7d, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x46, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6c, 0x65, 0x6d,
	0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73,
	0x61, 0x69, 0x2e, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x41, 0x74, 0x74, 0x72, 0x52, 0x08, 0x61, 0x74, 0x74, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x68, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e, 0x49, 0x73, 0x6f, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x22, 0xd6, 0x01, 0x0a, 0x21, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x37, 0x0a, 0x12, 0x69, 0x73, 0x6f, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x01, 0x48, 0x00, 0x52, 0x10, 0x69, 0x73, 0x6f,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x34, 0x0a, 0x10, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x02,
	0x48, 0x01, 0x52, 0x0f, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x88, 0x01, 0x01, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x69, 0x73, 0x6f, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x42, 0x13, 0x0a,
	0x11, 0x5f, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x22, 0x36, 0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x73, 0x6f, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x21, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6f, 0x69,
	0x64, 0x22, 0x24, 0x0a, 0x22, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x89, 0x01, 0x0a, 0x27, 0x47, 0x65, 0x74, 0x49,
	0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x4c, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69,
	0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69,
	0x2e, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x52, 0x08, 0x61, 0x74, 0x74, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x74, 0x0a, 0x28, 0x47, 0x65, 0x74, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x48, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e,
	0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x2a, 0x89, 0x01, 0x0a, 0x12, 0x49, 0x73,
	0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x74, 0x74, 0x72,
	0x12, 0x24, 0x0a, 0x20, 0x49, 0x53, 0x4f, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x47, 0x52,
	0x4f, 0x55, 0x50, 0x5f, 0x41, 0x54, 0x54, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x49, 0x53, 0x4f, 0x4c, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x41, 0x54, 0x54, 0x52, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x10, 0x01, 0x12, 0x2e, 0x0a, 0x2a, 0x49, 0x53, 0x4f, 0x4c, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x41, 0x54, 0x54, 0x52, 0x5f, 0x49, 0x53,
	0x4f, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x4c,
	0x49, 0x53, 0x54, 0x10, 0x02, 0x2a, 0xad, 0x01, 0x0a, 0x18, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x74,
	0x74, 0x72, 0x12, 0x2b, 0x0a, 0x27, 0x49, 0x53, 0x4f, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x41, 0x54, 0x54,
	0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x32, 0x0a, 0x2e, 0x49, 0x53, 0x4f, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x47, 0x52, 0x4f,
	0x55, 0x50, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x41, 0x54, 0x54, 0x52, 0x5f, 0x49,
	0x53, 0x4f, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x49,
	0x44, 0x10, 0x01, 0x12, 0x30, 0x0a, 0x2c, 0x49, 0x53, 0x4f, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x41, 0x54,
	0x54, 0x52, 0x5f, 0x49, 0x53, 0x4f, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x42, 0x4a,
	0x45, 0x43, 0x54, 0x10, 0x02, 0x32, 0x82, 0x07, 0x0a, 0x0e, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x81, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x32, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x81, 0x01, 0x0a,
	0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x32, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x6c, 0x65, 0x6d, 0x6d,
	0x69, 0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61,
	0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x93, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12,
	0x38, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x73, 0x6f, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x6c, 0x65, 0x6d, 0x6d,
	0x69, 0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x93, 0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x38, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x39, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x73,
	0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x93, 0x01, 0x0a,
	0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x38, 0x2e, 0x6c, 0x65,
	0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x73, 0x61, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0xa5, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x3e, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e,
	0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3f, 0x2e, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e,
	0x67, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x73, 0x61, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x6c, 0x65, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x6c, 0x6f, 0x6e, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dataplane_standalone_proto_isolation_group_proto_rawDescOnce sync.Once
	file_dataplane_standalone_proto_isolation_group_proto_rawDescData = file_dataplane_standalone_proto_isolation_group_proto_rawDesc
)

func file_dataplane_standalone_proto_isolation_group_proto_rawDescGZIP() []byte {
	file_dataplane_standalone_proto_isolation_group_proto_rawDescOnce.Do(func() {
		file_dataplane_standalone_proto_isolation_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_dataplane_standalone_proto_isolation_group_proto_rawDescData)
	})
	return file_dataplane_standalone_proto_isolation_group_proto_rawDescData
}

var file_dataplane_standalone_proto_isolation_group_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dataplane_standalone_proto_isolation_group_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_dataplane_standalone_proto_isolation_group_proto_goTypes = []interface{}{
	(IsolationGroupAttr)(0),                          // 0: lemming.dataplane.sai.IsolationGroupAttr
	(IsolationGroupMemberAttr)(0),                    // 1: lemming.dataplane.sai.IsolationGroupMemberAttr
	(*CreateIsolationGroupRequest)(nil),              // 2: lemming.dataplane.sai.CreateIsolationGroupRequest
	(*CreateIsolationGroupResponse)(nil),             // 3: lemming.dataplane.sai.CreateIsolationGroupResponse
	(*RemoveIsolationGroupRequest)(nil),              // 4: lemming.dataplane.sai.RemoveIsolationGroupRequest
	(*RemoveIsolationGroupResponse)(nil),             // 5: lemming.dataplane.sai.RemoveIsolationGroupResponse
	(*GetIsolationGroupAttributeRequest)(nil),        // 6: lemming.dataplane.sai.GetIsolationGroupAttributeRequest
	(*GetIsolationGroupAttributeResponse)(nil),       // 7: lemming.dataplane.sai.GetIsolationGroupAttributeResponse
	(*CreateIsolationGroupMemberRequest)(nil),        // 8: lemming.dataplane.sai.CreateIsolationGroupMemberRequest
	(*CreateIsolationGroupMemberResponse)(nil),       // 9: lemming.dataplane.sai.CreateIsolationGroupMemberResponse
	(*RemoveIsolationGroupMemberRequest)(nil),        // 10: lemming.dataplane.sai.RemoveIsolationGroupMemberRequest
	(*RemoveIsolationGroupMemberResponse)(nil),       // 11: lemming.dataplane.sai.RemoveIsolationGroupMemberResponse
	(*GetIsolationGroupMemberAttributeRequest)(nil),  // 12: lemming.dataplane.sai.GetIsolationGroupMemberAttributeRequest
	(*GetIsolationGroupMemberAttributeResponse)(nil), // 13: lemming.dataplane.sai.GetIsolationGroupMemberAttributeResponse
	(IsolationGroupType)(0),                          // 14: lemming.dataplane.sai.IsolationGroupType
	(*IsolationGroupAttribute)(nil),                  // 15: lemming.dataplane.sai.IsolationGroupAttribute
	(*IsolationGroupMemberAttribute)(nil),            // 16: lemming.dataplane.sai.IsolationGroupMemberAttribute
}
var file_dataplane_standalone_proto_isolation_group_proto_depIdxs = []int32{
	14, // 0: lemming.dataplane.sai.CreateIsolationGroupRequest.type:type_name -> lemming.dataplane.sai.IsolationGroupType
	0,  // 1: lemming.dataplane.sai.GetIsolationGroupAttributeRequest.attr_type:type_name -> lemming.dataplane.sai.IsolationGroupAttr
	15, // 2: lemming.dataplane.sai.GetIsolationGroupAttributeResponse.attr:type_name -> lemming.dataplane.sai.IsolationGroupAttribute
	1,  // 3: lemming.dataplane.sai.GetIsolationGroupMemberAttributeRequest.attr_type:type_name -> lemming.dataplane.sai.IsolationGroupMemberAttr
	16, // 4: lemming.dataplane.sai.GetIsolationGroupMemberAttributeResponse.attr:type_name -> lemming.dataplane.sai.IsolationGroupMemberAttribute
	2,  // 5: lemming.dataplane.sai.IsolationGroup.CreateIsolationGroup:input_type -> lemming.dataplane.sai.CreateIsolationGroupRequest
	4,  // 6: lemming.dataplane.sai.IsolationGroup.RemoveIsolationGroup:input_type -> lemming.dataplane.sai.RemoveIsolationGroupRequest
	6,  // 7: lemming.dataplane.sai.IsolationGroup.GetIsolationGroupAttribute:input_type -> lemming.dataplane.sai.GetIsolationGroupAttributeRequest
	8,  // 8: lemming.dataplane.sai.IsolationGroup.CreateIsolationGroupMember:input_type -> lemming.dataplane.sai.CreateIsolationGroupMemberRequest
	10, // 9: lemming.dataplane.sai.IsolationGroup.RemoveIsolationGroupMember:input_type -> lemming.dataplane.sai.RemoveIsolationGroupMemberRequest
	12, // 10: lemming.dataplane.sai.IsolationGroup.GetIsolationGroupMemberAttribute:input_type -> lemming.dataplane.sai.GetIsolationGroupMemberAttributeRequest
	3,  // 11: lemming.dataplane.sai.IsolationGroup.CreateIsolationGroup:output_type -> lemming.dataplane.sai.CreateIsolationGroupResponse
	5,  // 12: lemming.dataplane.sai.IsolationGroup.RemoveIsolationGroup:output_type -> lemming.dataplane.sai.RemoveIsolationGroupResponse
	7,  // 13: lemming.dataplane.sai.IsolationGroup.GetIsolationGroupAttribute:output_type -> lemming.dataplane.sai.GetIsolationGroupAttributeResponse
	9,  // 14: lemming.dataplane.sai.IsolationGroup.CreateIsolationGroupMember:output_type -> lemming.dataplane.sai.CreateIsolationGroupMemberResponse
	11, // 15: lemming.dataplane.sai.IsolationGroup.RemoveIsolationGroupMember:output_type -> lemming.dataplane.sai.RemoveIsolationGroupMemberResponse
	13, // 16: lemming.dataplane.sai.IsolationGroup.GetIsolationGroupMemberAttribute:output_type -> lemming.dataplane.sai.GetIsolationGroupMemberAttributeResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dataplane_standalone_proto_isolation_group_proto_init() }
func file_dataplane_standalone_proto_isolation_group_proto_init() {
	if File_dataplane_standalone_proto_isolation_group_proto != nil {
		return
	}
	file_dataplane_standalone_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIsolationGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIsolationGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveIsolationGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveIsolationGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIsolationGroupAttributeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIsolationGroupAttributeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIsolationGroupMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIsolationGroupMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveIsolationGroupMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveIsolationGroupMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIsolationGroupMemberAttributeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataplane_standalone_proto_isolation_group_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIsolationGroupMemberAttributeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dataplane_standalone_proto_isolation_group_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_dataplane_standalone_proto_isolation_group_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dataplane_standalone_proto_isolation_group_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataplane_standalone_proto_isolation_group_proto_goTypes,
		DependencyIndexes: file_dataplane_standalone_proto_isolation_group_proto_depIdxs,
		EnumInfos:         file_dataplane_standalone_proto_isolation_group_proto_enumTypes,
		MessageInfos:      file_dataplane_standalone_proto_isolation_group_proto_msgTypes,
	}.Build()
	File_dataplane_standalone_proto_isolation_group_proto = out.File
	file_dataplane_standalone_proto_isolation_group_proto_rawDesc = nil
	file_dataplane_standalone_proto_isolation_group_proto_goTypes = nil
	file_dataplane_standalone_proto_isolation_group_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IsolationGroupClient is the client API for IsolationGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IsolationGroupClient interface {
	CreateIsolationGroup(ctx context.Context, in *CreateIsolationGroupRequest, opts ...grpc.CallOption) (*CreateIsolationGroupResponse, error)
	RemoveIsolationGroup(ctx context.Context, in *RemoveIsolationGroupRequest, opts ...grpc.CallOption) (*RemoveIsolationGroupResponse, error)
	GetIsolationGroupAttribute(ctx context.Context, in *GetIsolationGroupAttributeRequest, opts ...grpc.CallOption) (*GetIsolationGroupAttributeResponse, error)
	CreateIsolationGroupMember(ctx context.Context, in *CreateIsolationGroupMemberRequest, opts ...grpc.CallOption) (*CreateIsolationGroupMemberResponse, error)
	RemoveIsolationGroupMember(ctx context.Context, in *RemoveIsolationGroupMemberRequest, opts ...grpc.CallOption) (*RemoveIsolationGroupMemberResponse, error)
	GetIsolationGroupMemberAttribute(ctx context.Context, in *GetIsolationGroupMemberAttributeRequest, opts ...grpc.CallOption) (*GetIsolationGroupMemberAttributeResponse, error)
}

type isolationGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewIsolationGroupClient(cc grpc.ClientConnInterface) IsolationGroupClient {
	return &isolationGroupClient{cc}
}

func (c *isolationGroupClient) CreateIsolationGroup(ctx context.Context, in *CreateIsolationGroupRequest, opts ...grpc.CallOption) (*CreateIsolationGroupResponse, error) {
	out := new(CreateIsolationGroupResponse)
	err := c.cc.Invoke(ctx, "/lemming.dataplane.sai.IsolationGroup/CreateIsolationGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isolationGroupClient) RemoveIsolationGroup(ctx context.Context, in *RemoveIsolationGroupRequest, opts ...grpc.CallOption) (*RemoveIsolationGroupResponse, error) {
	out := new(RemoveIsolationGroupResponse)
	err := c.cc.Invoke(ctx, "/lemming.dataplane.sai.IsolationGroup/RemoveIsolationGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isolationGroupClient) GetIsolationGroupAttribute(ctx context.Context, in *GetIsolationGroupAttributeRequest, opts ...grpc.CallOption) (*GetIsolationGroupAttributeResponse, error) {
	out := new(GetIsolationGroupAttributeResponse)
	err := c.cc.Invoke(ctx, "/lemming.dataplane.sai.IsolationGroup/GetIsolationGroupAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isolationGroupClient) CreateIsolationGroupMember(ctx context.Context, in *CreateIsolationGroupMemberRequest, opts ...grpc.CallOption) (*CreateIsolationGroupMemberResponse, error) {
	out := new(CreateIsolationGroupMemberResponse)
	err := c.cc.Invoke(ctx, "/lemming.dataplane.sai.IsolationGroup/CreateIsolationGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isolationGroupClient) RemoveIsolationGroupMember(ctx context.Context, in *RemoveIsolationGroupMemberRequest, opts ...grpc.CallOption) (*RemoveIsolationGroupMemberResponse, error) {
	out := new(RemoveIsolationGroupMemberResponse)
	err := c.cc.Invoke(ctx, "/lemming.dataplane.sai.IsolationGroup/RemoveIsolationGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isolationGroupClient) GetIsolationGroupMemberAttribute(ctx context.Context, in *GetIsolationGroupMemberAttributeRequest, opts ...grpc.CallOption) (*GetIsolationGroupMemberAttributeResponse, error) {
	out := new(GetIsolationGroupMemberAttributeResponse)
	err := c.cc.Invoke(ctx, "/lemming.dataplane.sai.IsolationGroup/GetIsolationGroupMemberAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IsolationGroupServer is the server API for IsolationGroup service.
type IsolationGroupServer interface {
	CreateIsolationGroup(context.Context, *CreateIsolationGroupRequest) (*CreateIsolationGroupResponse, error)
	RemoveIsolationGroup(context.Context, *RemoveIsolationGroupRequest) (*RemoveIsolationGroupResponse, error)
	GetIsolationGroupAttribute(context.Context, *GetIsolationGroupAttributeRequest) (*GetIsolationGroupAttributeResponse, error)
	CreateIsolationGroupMember(context.Context, *CreateIsolationGroupMemberRequest) (*CreateIsolationGroupMemberResponse, error)
	RemoveIsolationGroupMember(context.Context, *RemoveIsolationGroupMemberRequest) (*RemoveIsolationGroupMemberResponse, error)
	GetIsolationGroupMemberAttribute(context.Context, *GetIsolationGroupMemberAttributeRequest) (*GetIsolationGroupMemberAttributeResponse, error)
}

// UnimplementedIsolationGroupServer can be embedded to have forward compatible implementations.
type UnimplementedIsolationGroupServer struct {
}

func (*UnimplementedIsolationGroupServer) CreateIsolationGroup(context.Context, *CreateIsolationGroupRequest) (*CreateIsolationGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIsolationGroup not implemented")
}
func (*UnimplementedIsolationGroupServer) RemoveIsolationGroup(context.Context, *RemoveIsolationGroupRequest) (*RemoveIsolationGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveIsolationGroup not implemented")
}
func (*UnimplementedIsolationGroupServer) GetIsolationGroupAttribute(context.Context, *GetIsolationGroupAttributeRequest) (*GetIsolationGroupAttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIsolationGroupAttribute not implemented")
}
func (*UnimplementedIsolationGroupServer) CreateIsolationGroupMember(context.Context, *CreateIsolationGroupMemberRequest) (*CreateIsolationGroupMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIsolationGroupMember not implemented")
}
func (*UnimplementedIsolationGroupServer) RemoveIsolationGroupMember(context.Context, *RemoveIsolationGroupMemberRequest) (*RemoveIsolationGroupMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveIsolationGroupMember not implemented")
}
func (*UnimplementedIsolationGroupServer) GetIsolationGroupMemberAttribute(context.Context, *GetIsolationGroupMemberAttributeRequest) (*GetIsolationGroupMemberAttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIsolationGroupMemberAttribute not implemented")
}

func RegisterIsolationGroupServer(s *grpc.Server, srv IsolationGroupServer) {
	s.RegisterService(&_IsolationGroup_serviceDesc, srv)
}

func _IsolationGroup_CreateIsolationGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIsolationGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolationGroupServer).CreateIsolationGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lemming.dataplane.sai.IsolationGroup/CreateIsolationGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolationGroupServer).CreateIsolationGroup(ctx, req.(*CreateIsolationGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IsolationGroup_RemoveIsolationGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveIsolationGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolationGroupServer).RemoveIsolationGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lemming.dataplane.sai.IsolationGroup/RemoveIsolationGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolationGroupServer).RemoveIsolationGroup(ctx, req.(*RemoveIsolationGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IsolationGroup_GetIsolationGroupAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIsolationGroupAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolationGroupServer).GetIsolationGroupAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lemming.dataplane.sai.IsolationGroup/GetIsolationGroupAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolationGroupServer).GetIsolationGroupAttribute(ctx, req.(*GetIsolationGroupAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IsolationGroup_CreateIsolationGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIsolationGroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolationGroupServer).CreateIsolationGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lemming.dataplane.sai.IsolationGroup/CreateIsolationGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolationGroupServer).CreateIsolationGroupMember(ctx, req.(*CreateIsolationGroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IsolationGroup_RemoveIsolationGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveIsolationGroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolationGroupServer).RemoveIsolationGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lemming.dataplane.sai.IsolationGroup/RemoveIsolationGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolationGroupServer).RemoveIsolationGroupMember(ctx, req.(*RemoveIsolationGroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IsolationGroup_GetIsolationGroupMemberAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIsolationGroupMemberAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolationGroupServer).GetIsolationGroupMemberAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lemming.dataplane.sai.IsolationGroup/GetIsolationGroupMemberAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolationGroupServer).GetIsolationGroupMemberAttribute(ctx, req.(*GetIsolationGroupMemberAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IsolationGroup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lemming.dataplane.sai.IsolationGroup",
	HandlerType: (*IsolationGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIsolationGroup",
			Handler:    _IsolationGroup_CreateIsolationGroup_Handler,
		},
		{
			MethodName: "RemoveIsolationGroup",
			Handler:    _IsolationGroup_RemoveIsolationGroup_Handler,
		},
		{
			MethodName: "GetIsolationGroupAttribute",
			Handler:    _IsolationGroup_GetIsolationGroupAttribute_Handler,
		},
		{
			MethodName: "CreateIsolationGroupMember",
			Handler:    _IsolationGroup_CreateIsolationGroupMember_Handler,
		},
		{
			MethodName: "RemoveIsolationGroupMember",
			Handler:    _IsolationGroup_RemoveIsolationGroupMember_Handler,
		},
		{
			MethodName: "GetIsolationGroupMemberAttribute",
			Handler:    _IsolationGroup_GetIsolationGroupMemberAttribute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dataplane/standalone/proto/isolation_group.proto",
}
