load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "debug",
    srcs = ["debug.go"],
    importpath = "github.com/openconfig/lemming/internal/debug",
    visibility = ["//:__subpackages__"],
)
