load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "netinstisis",
    srcs = [
        "netinstisis-0.go",
        "netinstisis-1.go",
        "netinstisis-2.go",
        "netinstisis-3.go",
        "netinstisis-4.go",
        "netinstisis-5.go",
        "netinstisis-6.go",
        "netinstisis-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/netinstisis",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
