load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "netinstbgp",
    srcs = [
        "netinstbgp-0.go",
        "netinstbgp-1.go",
        "netinstbgp-2.go",
        "netinstbgp-3.go",
        "netinstbgp-4.go",
        "netinstbgp-5.go",
        "netinstbgp-6.go",
        "netinstbgp-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/netinstbgp",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
