# permissions for end users to view lemmings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lemming-viewer-role
rules:
- apiGroups:
  - lemming.openconfig.net
  resources:
  - lemmings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lemming.openconfig.net
  resources:
  - lemmings/status
  verbs:
  - get
