version: "2"
linters:
  default: none
  enable:
    - goconst
    - gocritic
    - gosec
    - govet
    - revive
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-blank: true
    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - appendAssign
    gosec:
      excludes:
        - G204
        - G115
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
      - path: gribi/gribi.go
        text: grpc.Dial is deprecated
    paths:
      - gnmi/oc
      - integration_tests
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - gnmi/oc
      - integration_tests
      - third_party$
      - builtin$
      - examples$
