load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "interfaces",
    srcs = [
        "interfaces-0.go",
        "interfaces-1.go",
        "interfaces-2.go",
        "interfaces-3.go",
        "interfaces-4.go",
        "interfaces-5.go",
        "interfaces-6.go",
        "interfaces-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/interfaces",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
