// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/sysrib/sysrib.proto

package sysrib

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sysrib_SetRoute_FullMethodName = "/sysrib.Sysrib/SetRoute"
)

// SysribClient is the client API for Sysrib service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysribClient interface {
	SetRoute(ctx context.Context, in *SetRouteRequest, opts ...grpc.CallOption) (*SetRouteResponse, error)
}

type sysribClient struct {
	cc grpc.ClientConnInterface
}

func NewSysribClient(cc grpc.ClientConnInterface) SysribClient {
	return &sysribClient{cc}
}

func (c *sysribClient) SetRoute(ctx context.Context, in *SetRouteRequest, opts ...grpc.CallOption) (*SetRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRouteResponse)
	err := c.cc.Invoke(ctx, Sysrib_SetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysribServer is the server API for Sysrib service.
// All implementations should embed UnimplementedSysribServer
// for forward compatibility.
type SysribServer interface {
	SetRoute(context.Context, *SetRouteRequest) (*SetRouteResponse, error)
}

// UnimplementedSysribServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysribServer struct{}

func (UnimplementedSysribServer) SetRoute(context.Context, *SetRouteRequest) (*SetRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRoute not implemented")
}
func (UnimplementedSysribServer) testEmbeddedByValue() {}

// UnsafeSysribServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysribServer will
// result in compilation errors.
type UnsafeSysribServer interface {
	mustEmbedUnimplementedSysribServer()
}

func RegisterSysribServer(s grpc.ServiceRegistrar, srv SysribServer) {
	// If the following call pancis, it indicates UnimplementedSysribServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sysrib_ServiceDesc, srv)
}

func _Sysrib_SetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysribServer).SetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sysrib_SetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysribServer).SetRoute(ctx, req.(*SetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sysrib_ServiceDesc is the grpc.ServiceDesc for Sysrib service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sysrib_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysrib.Sysrib",
	HandlerType: (*SysribServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRoute",
			Handler:    _Sysrib_SetRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sysrib/sysrib.proto",
}
