load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "lemmingutil",
    srcs = ["util.go"],
    importpath = "github.com/openconfig/lemming/internal/lemmingutil",
    visibility = ["//:__subpackages__"],
)
