load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "networkinstance",
    srcs = [
        "networkinstance-0.go",
        "networkinstance-1.go",
        "networkinstance-2.go",
        "networkinstance-3.go",
        "networkinstance-4.go",
        "networkinstance-5.go",
        "networkinstance-6.go",
        "networkinstance-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/networkinstance",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "//gnmi/oc/netinstbgp",
        "//gnmi/oc/netinstisis",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
