load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "platform",
    srcs = [
        "platform-0.go",
        "platform-1.go",
        "platform-2.go",
        "platform-3.go",
        "platform-4.go",
        "platform-5.go",
        "platform-6.go",
        "platform-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/platform",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
