load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "qos",
    srcs = [
        "qos-0.go",
        "qos-1.go",
        "qos-2.go",
        "qos-3.go",
        "qos-4.go",
        "qos-5.go",
        "qos-6.go",
        "qos-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/qos",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
