load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "relayagent",
    srcs = [
        "relayagent-0.go",
        "relayagent-1.go",
        "relayagent-2.go",
        "relayagent-3.go",
        "relayagent-4.go",
        "relayagent-5.go",
        "relayagent-6.go",
        "relayagent-7.go",
    ],
    importpath = "github.com/openconfig/lemming/gnmi/oc/relayagent",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi/oc",
        "@com_github_openconfig_ygnmi//ygnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)
