# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
      - name: Restore Bazel Cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bazel-build-
            ${{ runner.os }}-bazel-
      - name: Free additional disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          {
            echo "ANDROID_HOME="
            echo "ANDROID_SDK_ROOT="
            echo "ANDROID_NDK_ROOT="
            echo "ANDROID_NDK_HOME="
          } >> "$GITHUB_ENV"
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo mv "${HOME}/.cache" /mnt/cache || (sudo mkdir /mnt/cache && sudo chown "${USER}:" /mnt/cache)
          ln -s /mnt/cache "${HOME}/.cache"
      - name: Install pcap
        run: |
          sudo apt-get install libpcap-dev libnl-genl-3-dev libnl-3-dev
      - name: Build Lemming
        run: bazel build //...
      - name: Save Bazel Cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: github.ref == 'refs/heads/main'
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-build-${{ github.sha }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
      - name: Restore Bazel Cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bazel-test-
            ${{ runner.os }}-bazel-
      - name: Free additional disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          {
            echo "ANDROID_HOME="
            echo "ANDROID_SDK_ROOT="
            echo "ANDROID_NDK_ROOT="
            echo "ANDROID_NDK_HOME="
          } >> "$GITHUB_ENV"
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo mv "${HOME}/.cache" /mnt/cache || (sudo mkdir /mnt/cache && sudo chown "${USER}:" /mnt/cache)
          ln -s /mnt/cache "${HOME}/.cache"
      - name: Install pcap
        run: |
          sudo apt-get install libpcap-dev libnl-genl-3-dev libnl-3-dev
      - name: Test
        run: make coverage
      - name: Coveralls
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          file: bazel-out/_coverage/_coverage_report.dat
          format: lcov
      - run: |
          make test-race
      - name: Save Bazel Cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: github.ref == 'refs/heads/main'
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-test-${{ github.sha }}
